// A bundled offline dataset of Indian cities for the city typeahead (F7).
// No network or API call: the list ships with the app so the typeahead works
// offline, and a free-text fallback handles anything not listed here (an old
// mandal in a village that never makes a tier-2/tier-3 list still types it in).
// Every `state` matches the canonical names in ./states.ts exactly, so a picked
// city can fill the state field without a lookup table.

export interface CityEntry {
  city: string
  state: string
}

export const INDIAN_CITIES: CityEntry[] = [
  { city: "Abohar", state: "Punjab" },
  { city: "Adilabad", state: "Telangana" },
  { city: "Adoni", state: "Andhra Pradesh" },
  { city: "Agartala", state: "Tripura" },
  { city: "Agatti", state: "Lakshadweep" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Ahmednagar", state: "Maharashtra" },
  { city: "Aizawl", state: "Mizoram" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Akola", state: "Maharashtra" },
  { city: "Alappuzha", state: "Kerala" },
  { city: "Alibag", state: "Maharashtra" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Alipurduar", state: "West Bengal" },
  { city: "Almora", state: "Uttarakhand" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Amaravati", state: "Andhra Pradesh" },
  { city: "Ambala", state: "Haryana" },
  { city: "Ambassa", state: "Tripura" },
  { city: "Ambernath", state: "Maharashtra" },
  { city: "Ambikapur", state: "Chhattisgarh" },
  { city: "Ambur", state: "Tamil Nadu" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Amreli", state: "Gujarat" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Amroha", state: "Uttar Pradesh" },
  { city: "Anand", state: "Gujarat" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Anantnag", state: "Jammu & Kashmir" },
  { city: "Angul", state: "Odisha" },
  { city: "Ankleshwar", state: "Gujarat" },
  { city: "Arrah", state: "Bihar" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Aurangabad", state: "Bihar" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Avadi", state: "Tamil Nadu" },
  { city: "Ayodhya", state: "Uttar Pradesh" },
  { city: "Azamgarh", state: "Uttar Pradesh" },
  { city: "Baddi", state: "Himachal Pradesh" },
  { city: "Badlapur", state: "Maharashtra" },
  { city: "Bagalkot", state: "Karnataka" },
  { city: "Baghmara", state: "Meghalaya" },
  { city: "Bahadurgarh", state: "Haryana" },
  { city: "Baharampur", state: "West Bengal" },
  { city: "Bahraich", state: "Uttar Pradesh" },
  { city: "Balaghat", state: "Madhya Pradesh" },
  { city: "Balasore", state: "Odisha" },
  { city: "Ballari", state: "Karnataka" },
  { city: "Ballia", state: "Uttar Pradesh" },
  { city: "Balurghat", state: "West Bengal" },
  { city: "Banda", state: "Uttar Pradesh" },
  { city: "Bankura", state: "West Bengal" },
  { city: "Banswara", state: "Rajasthan" },
  { city: "Barabanki", state: "Uttar Pradesh" },
  { city: "Baramati", state: "Maharashtra" },
  { city: "Baramulla", state: "Jammu & Kashmir" },
  { city: "Barasat", state: "West Bengal" },
  { city: "Barbil", state: "Odisha" },
  { city: "Bardhaman", state: "West Bengal" },
  { city: "Bardoli", state: "Gujarat" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Bargarh", state: "Odisha" },
  { city: "Baripada", state: "Odisha" },
  { city: "Barmer", state: "Rajasthan" },
  { city: "Barnala", state: "Punjab" },
  { city: "Barpeta", state: "Assam" },
  { city: "Barshi", state: "Maharashtra" },
  { city: "Basti", state: "Uttar Pradesh" },
  { city: "Batala", state: "Punjab" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Beawar", state: "Rajasthan" },
  { city: "Beed", state: "Maharashtra" },
  { city: "Begusarai", state: "Bihar" },
  { city: "Belagavi", state: "Karnataka" },
  { city: "Belonia", state: "Tripura" },
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Berhampur", state: "Odisha" },
  { city: "Bettiah", state: "Bihar" },
  { city: "Betul", state: "Madhya Pradesh" },
  { city: "Bhadrak", state: "Odisha" },
  { city: "Bhadravati", state: "Karnataka" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Bharuch", state: "Gujarat" },
  { city: "Bhatapara", state: "Chhattisgarh" },
  { city: "Bhatpara", state: "West Bengal" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Bhimavaram", state: "Andhra Pradesh" },
  { city: "Bhind", state: "Madhya Pradesh" },
  { city: "Bhiwandi", state: "Maharashtra" },
  { city: "Bhiwani", state: "Haryana" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Bhuj", state: "Gujarat" },
  { city: "Bhusawal", state: "Maharashtra" },
  { city: "Bicholim", state: "Goa" },
  { city: "Bidar", state: "Karnataka" },
  { city: "Bihar Sharif", state: "Bihar" },
  { city: "Bijnor", state: "Uttar Pradesh" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Bilaspur", state: "Himachal Pradesh" },
  { city: "Bishnupur", state: "Manipur" },
  { city: "Boisar", state: "Maharashtra" },
  { city: "Bokaro", state: "Jharkhand" },
  { city: "Bomdila", state: "Arunachal Pradesh" },
  { city: "Bongaigaon", state: "Assam" },
  { city: "Botad", state: "Gujarat" },
  { city: "Bulandshahr", state: "Uttar Pradesh" },
  { city: "Buldhana", state: "Maharashtra" },
  { city: "Bundi", state: "Rajasthan" },
  { city: "Burhanpur", state: "Madhya Pradesh" },
  { city: "Buxar", state: "Bihar" },
  { city: "Chaibasa", state: "Jharkhand" },
  { city: "Chamba", state: "Himachal Pradesh" },
  { city: "Champhai", state: "Mizoram" },
  { city: "Chandannagar", state: "West Bengal" },
  { city: "Chandigarh", state: "Chandigarh" },
  { city: "Chandrapur", state: "Maharashtra" },
  { city: "Changanassery", state: "Kerala" },
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Cherthala", state: "Kerala" },
  { city: "Chhapra", state: "Bihar" },
  { city: "Chhatarpur", state: "Madhya Pradesh" },
  { city: "Chhatrapati Sambhajinagar", state: "Maharashtra" },
  { city: "Chhindwara", state: "Madhya Pradesh" },
  { city: "Chikkamagaluru", state: "Karnataka" },
  { city: "Chirala", state: "Andhra Pradesh" },
  { city: "Chirkunda", state: "Jharkhand" },
  { city: "Chirmiri", state: "Chhattisgarh" },
  { city: "Chitradurga", state: "Karnataka" },
  { city: "Chittoor", state: "Andhra Pradesh" },
  { city: "Chittorgarh", state: "Rajasthan" },
  { city: "Churachandpur", state: "Manipur" },
  { city: "Churu", state: "Rajasthan" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Cooch Behar", state: "West Bengal" },
  { city: "Cuddalore", state: "Tamil Nadu" },
  { city: "Curchorem", state: "Goa" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Dahod", state: "Gujarat" },
  { city: "Dalli-Rajhara", state: "Chhattisgarh" },
  { city: "Daman", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Damoh", state: "Madhya Pradesh" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Darjeeling", state: "West Bengal" },
  { city: "Datia", state: "Madhya Pradesh" },
  { city: "Dausa", state: "Rajasthan" },
  { city: "Davanagere", state: "Karnataka" },
  { city: "Deesa", state: "Gujarat" },
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Dehri", state: "Bihar" },
  { city: "Delhi", state: "Delhi" },
  { city: "Deoghar", state: "Jharkhand" },
  { city: "Deolali", state: "Maharashtra" },
  { city: "Deoria", state: "Uttar Pradesh" },
  { city: "Dewas", state: "Madhya Pradesh" },
  { city: "Dhamtari", state: "Chhattisgarh" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Dharamshala", state: "Himachal Pradesh" },
  { city: "Dharmanagar", state: "Tripura" },
  { city: "Dharmapuri", state: "Tamil Nadu" },
  { city: "Dhenkanal", state: "Odisha" },
  { city: "Dholpur", state: "Rajasthan" },
  { city: "Dhubri", state: "Assam" },
  { city: "Dhule", state: "Maharashtra" },
  { city: "Dibrugarh", state: "Assam" },
  { city: "Diglipur", state: "Andaman & Nicobar Islands" },
  { city: "Dimapur", state: "Nagaland" },
  { city: "Dindigul", state: "Tamil Nadu" },
  { city: "Diphu", state: "Assam" },
  { city: "Dispur", state: "Assam" },
  { city: "Diu", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Dombivli", state: "Maharashtra" },
  { city: "Dumka", state: "Jharkhand" },
  { city: "Durg", state: "Chhattisgarh" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Dwarka", state: "Gujarat" },
  { city: "Eluru", state: "Andhra Pradesh" },
  { city: "Erode", state: "Tamil Nadu" },
  { city: "Etah", state: "Uttar Pradesh" },
  { city: "Etawah", state: "Uttar Pradesh" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Faridkot", state: "Punjab" },
  { city: "Farrukhabad", state: "Uttar Pradesh" },
  { city: "Fatehabad", state: "Haryana" },
  { city: "Fatehpur", state: "Uttar Pradesh" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Firozpur", state: "Punjab" },
  { city: "Gadag", state: "Karnataka" },
  { city: "Gadchiroli", state: "Maharashtra" },
  { city: "Gandhidham", state: "Gujarat" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Gangavati", state: "Karnataka" },
  { city: "Gangtok", state: "Sikkim" },
  { city: "Gaya", state: "Bihar" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Ghazipur", state: "Uttar Pradesh" },
  { city: "Giridih", state: "Jharkhand" },
  { city: "Goalpara", state: "Assam" },
  { city: "Godhra", state: "Gujarat" },
  { city: "Gonda", state: "Uttar Pradesh" },
  { city: "Gondal", state: "Gujarat" },
  { city: "Gondia", state: "Maharashtra" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Greater Noida", state: "Uttar Pradesh" },
  { city: "Gudivada", state: "Andhra Pradesh" },
  { city: "Gumla", state: "Jharkhand" },
  { city: "Guna", state: "Madhya Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Gurdaspur", state: "Punjab" },
  { city: "Gurugram", state: "Haryana" },
  { city: "Guruvayur", state: "Kerala" },
  { city: "Guwahati", state: "Assam" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Gyalshing", state: "Sikkim" },
  { city: "Habra", state: "West Bengal" },
  { city: "Hailakandi", state: "Assam" },
  { city: "Hajipur", state: "Bihar" },
  { city: "Haldia", state: "West Bengal" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Hamirpur", state: "Himachal Pradesh" },
  { city: "Hansi", state: "Haryana" },
  { city: "Hanumangarh", state: "Rajasthan" },
  { city: "Hapur", state: "Uttar Pradesh" },
  { city: "Hardoi", state: "Uttar Pradesh" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Hassan", state: "Karnataka" },
  { city: "Hazaribagh", state: "Jharkhand" },
  { city: "Himatnagar", state: "Gujarat" },
  { city: "Hindupur", state: "Andhra Pradesh" },
  { city: "Hingoli", state: "Maharashtra" },
  { city: "Hisar", state: "Haryana" },
  { city: "Hoshiarpur", state: "Punjab" },
  { city: "Hospet", state: "Karnataka" },
  { city: "Hospete", state: "Karnataka" },
  { city: "Hosur", state: "Tamil Nadu" },
  { city: "Howrah", state: "West Bengal" },
  { city: "Hubballi", state: "Karnataka" },
  { city: "Hyderabad", state: "Telangana" },
  { city: "Ichalkaranji", state: "Maharashtra" },
  { city: "Idar", state: "Gujarat" },
  { city: "Imphal", state: "Manipur" },
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Itanagar", state: "Arunachal Pradesh" },
  { city: "Itarsi", state: "Madhya Pradesh" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Jagdalpur", state: "Chhattisgarh" },
  { city: "Jagtial", state: "Telangana" },
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Jaisalmer", state: "Rajasthan" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Jalgaon", state: "Maharashtra" },
  { city: "Jalna", state: "Maharashtra" },
  { city: "Jalpaiguri", state: "West Bengal" },
  { city: "Jamalpur", state: "Bihar" },
  { city: "Jammu", state: "Jammu & Kashmir" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Jaunpur", state: "Uttar Pradesh" },
  { city: "Jehanabad", state: "Bihar" },
  { city: "Jetpur", state: "Gujarat" },
  { city: "Jeypore", state: "Odisha" },
  { city: "Jhalawar", state: "Rajasthan" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Jharsuguda", state: "Odisha" },
  { city: "Jhunjhunu", state: "Rajasthan" },
  { city: "Jind", state: "Haryana" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Jorethang", state: "Sikkim" },
  { city: "Jorhat", state: "Assam" },
  { city: "Jowai", state: "Meghalaya" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Kadapa", state: "Andhra Pradesh" },
  { city: "Kadi", state: "Gujarat" },
  { city: "Kailashahar", state: "Tripura" },
  { city: "Kaithal", state: "Haryana" },
  { city: "Kakching", state: "Manipur" },
  { city: "Kakinada", state: "Andhra Pradesh" },
  { city: "Kalaburagi", state: "Karnataka" },
  { city: "Kalol", state: "Gujarat" },
  { city: "Kalyan-Dombivli", state: "Maharashtra" },
  { city: "Kanchipuram", state: "Tamil Nadu" },
  { city: "Kangra", state: "Himachal Pradesh" },
  { city: "Kannur", state: "Kerala" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Kapurthala", state: "Punjab" },
  { city: "Karad", state: "Maharashtra" },
  { city: "Karaikal", state: "Puducherry" },
  { city: "Karaikudi", state: "Tamil Nadu" },
  { city: "Kargil", state: "Ladakh" },
  { city: "Karimganj", state: "Assam" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Karur", state: "Tamil Nadu" },
  { city: "Karwar", state: "Karnataka" },
  { city: "Kasaragod", state: "Kerala" },
  { city: "Kasganj", state: "Uttar Pradesh" },
  { city: "Kashipur", state: "Uttarakhand" },
  { city: "Kathua", state: "Jammu & Kashmir" },
  { city: "Katihar", state: "Bihar" },
  { city: "Katni", state: "Madhya Pradesh" },
  { city: "Kavaratti", state: "Lakshadweep" },
  { city: "Kayamkulam", state: "Kerala" },
  { city: "Kendujhar", state: "Odisha" },
  { city: "Keshod", state: "Gujarat" },
  { city: "Khammam", state: "Telangana" },
  { city: "Khandwa", state: "Madhya Pradesh" },
  { city: "Khanna", state: "Punjab" },
  { city: "Kharagpur", state: "West Bengal" },
  { city: "Khargone", state: "Madhya Pradesh" },
  { city: "Kishanganj", state: "Bihar" },
  { city: "Kishangarh", state: "Rajasthan" },
  { city: "Kochi", state: "Kerala" },
  { city: "Kohima", state: "Nagaland" },
  { city: "Kolar", state: "Karnataka" },
  { city: "Kolasib", state: "Mizoram" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Kolkata", state: "West Bengal" },
  { city: "Kollam", state: "Kerala" },
  { city: "Kopargaon", state: "Maharashtra" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Kotdwar", state: "Uttarakhand" },
  { city: "Kothagudem", state: "Telangana" },
  { city: "Kottayam", state: "Kerala" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Krishnagiri", state: "Tamil Nadu" },
  { city: "Krishnanagar", state: "West Bengal" },
  { city: "Kullu", state: "Himachal Pradesh" },
  { city: "Kumbakonam", state: "Tamil Nadu" },
  { city: "Kupwara", state: "Jammu & Kashmir" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Kurukshetra", state: "Haryana" },
  { city: "Lakhimpur", state: "Uttar Pradesh" },
  { city: "Latur", state: "Maharashtra" },
  { city: "Leh", state: "Ladakh" },
  { city: "Lonavala", state: "Maharashtra" },
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Ludhiana", state: "Punjab" },
  { city: "Lunglei", state: "Mizoram" },
  { city: "Machilipatnam", state: "Andhra Pradesh" },
  { city: "Madhubani", state: "Bihar" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Mahabaleshwar", state: "Maharashtra" },
  { city: "Mahasamund", state: "Chhattisgarh" },
  { city: "Mahbubnagar", state: "Telangana" },
  { city: "Mahe", state: "Puducherry" },
  { city: "Mainpuri", state: "Uttar Pradesh" },
  { city: "Malappuram", state: "Kerala" },
  { city: "Malda", state: "West Bengal" },
  { city: "Malegaon", state: "Maharashtra" },
  { city: "Malerkotla", state: "Punjab" },
  { city: "Manali", state: "Himachal Pradesh" },
  { city: "Mancherial", state: "Telangana" },
  { city: "Mandi", state: "Himachal Pradesh" },
  { city: "Mandsaur", state: "Madhya Pradesh" },
  { city: "Mandya", state: "Karnataka" },
  { city: "Mangaluru", state: "Karnataka" },
  { city: "Mangan", state: "Sikkim" },
  { city: "Mangrol", state: "Gujarat" },
  { city: "Manjeri", state: "Kerala" },
  { city: "Mapusa", state: "Goa" },
  { city: "Margao", state: "Goa" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Mau", state: "Uttar Pradesh" },
  { city: "Medininagar", state: "Jharkhand" },
  { city: "Medinipur", state: "West Bengal" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Mehsana", state: "Gujarat" },
  { city: "Mettur", state: "Tamil Nadu" },
  { city: "Minicoy", state: "Lakshadweep" },
  { city: "Mira-Bhayandar", state: "Maharashtra" },
  { city: "Miraj", state: "Maharashtra" },
  { city: "Miryalaguda", state: "Telangana" },
  { city: "Mirzapur", state: "Uttar Pradesh" },
  { city: "Modasa", state: "Gujarat" },
  { city: "Moga", state: "Punjab" },
  { city: "Mohali", state: "Punjab" },
  { city: "Mokokchung", state: "Nagaland" },
  { city: "Mon", state: "Nagaland" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Morbi", state: "Gujarat" },
  { city: "Morena", state: "Madhya Pradesh" },
  { city: "Motihari", state: "Bihar" },
  { city: "Mount Abu", state: "Rajasthan" },
  { city: "Muktsar", state: "Punjab" },
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Mundra", state: "Gujarat" },
  { city: "Munger", state: "Bihar" },
  { city: "Mussoorie", state: "Uttarakhand" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Mysuru", state: "Karnataka" },
  { city: "Nabadwip", state: "West Bengal" },
  { city: "Nabha", state: "Punjab" },
  { city: "Nadiad", state: "Gujarat" },
  { city: "Nagaon", state: "Assam" },
  { city: "Nagapattinam", state: "Tamil Nadu" },
  { city: "Nagaur", state: "Rajasthan" },
  { city: "Nagda", state: "Madhya Pradesh" },
  { city: "Nagercoil", state: "Tamil Nadu" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Nahan", state: "Himachal Pradesh" },
  { city: "Naharlagun", state: "Arunachal Pradesh" },
  { city: "Nainital", state: "Uttarakhand" },
  { city: "Nalagarh", state: "Himachal Pradesh" },
  { city: "Nalgonda", state: "Telangana" },
  { city: "Namakkal", state: "Tamil Nadu" },
  { city: "Namchi", state: "Sikkim" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Nandurbar", state: "Maharashtra" },
  { city: "Nandyal", state: "Andhra Pradesh" },
  { city: "Narasaraopet", state: "Andhra Pradesh" },
  { city: "Narmadapuram", state: "Madhya Pradesh" },
  { city: "Narnaul", state: "Haryana" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Nathdwara", state: "Rajasthan" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Navsari", state: "Gujarat" },
  { city: "Nawada", state: "Bihar" },
  { city: "Neemuch", state: "Madhya Pradesh" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "New Delhi", state: "Delhi" },
  { city: "Nirmal", state: "Telangana" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Nongstoin", state: "Meghalaya" },
  { city: "North Lakhimpur", state: "Assam" },
  { city: "Okha", state: "Gujarat" },
  { city: "Ongole", state: "Andhra Pradesh" },
  { city: "Orai", state: "Uttar Pradesh" },
  { city: "Osmanabad", state: "Maharashtra" },
  { city: "Ottapalam", state: "Kerala" },
  { city: "Palakkad", state: "Kerala" },
  { city: "Palampur", state: "Himachal Pradesh" },
  { city: "Palanpur", state: "Gujarat" },
  { city: "Palghar", state: "Maharashtra" },
  { city: "Pali", state: "Rajasthan" },
  { city: "Palitana", state: "Gujarat" },
  { city: "Palwal", state: "Haryana" },
  { city: "Panaji", state: "Goa" },
  { city: "Panchkula", state: "Haryana" },
  { city: "Pandharpur", state: "Maharashtra" },
  { city: "Panipat", state: "Haryana" },
  { city: "Panvel", state: "Maharashtra" },
  { city: "Paradip", state: "Odisha" },
  { city: "Parbhani", state: "Maharashtra" },
  { city: "Pasighat", state: "Arunachal Pradesh" },
  { city: "Patan", state: "Gujarat" },
  { city: "Pathanamthitta", state: "Kerala" },
  { city: "Pathankot", state: "Punjab" },
  { city: "Patiala", state: "Punjab" },
  { city: "Patna", state: "Bihar" },
  { city: "Pauri", state: "Uttarakhand" },
  { city: "Perinthalmanna", state: "Kerala" },
  { city: "Petlad", state: "Gujarat" },
  { city: "Phagwara", state: "Punjab" },
  { city: "Phusro", state: "Jharkhand" },
  { city: "Pilibhit", state: "Uttar Pradesh" },
  { city: "Pimpri-Chinchwad", state: "Maharashtra" },
  { city: "Pithampur", state: "Madhya Pradesh" },
  { city: "Pithoragarh", state: "Uttarakhand" },
  { city: "Pollachi", state: "Tamil Nadu" },
  { city: "Ponda", state: "Goa" },
  { city: "Ponnani", state: "Kerala" },
  { city: "Porbandar", state: "Gujarat" },
  { city: "Port Blair", state: "Andaman & Nicobar Islands" },
  { city: "Prayagraj", state: "Uttar Pradesh" },
  { city: "Proddatur", state: "Andhra Pradesh" },
  { city: "Puducherry", state: "Puducherry" },
  { city: "Pudukkottai", state: "Tamil Nadu" },
  { city: "Pulwama", state: "Jammu & Kashmir" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Puri", state: "Odisha" },
  { city: "Purnia", state: "Bihar" },
  { city: "Purulia", state: "West Bengal" },
  { city: "Pushkar", state: "Rajasthan" },
  { city: "Raebareli", state: "Uttar Pradesh" },
  { city: "Raichur", state: "Karnataka" },
  { city: "Raiganj", state: "West Bengal" },
  { city: "Raigarh", state: "Chhattisgarh" },
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Rajapalayam", state: "Tamil Nadu" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Rajnandgaon", state: "Chhattisgarh" },
  { city: "Rajouri", state: "Jammu & Kashmir" },
  { city: "Rajpura", state: "Punjab" },
  { city: "Ramagundam", state: "Telangana" },
  { city: "Ramgarh", state: "Jharkhand" },
  { city: "Ramnagar", state: "Uttarakhand" },
  { city: "Rampur", state: "Uttar Pradesh" },
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Ranebennuru", state: "Karnataka" },
  { city: "Rangat", state: "Andaman & Nicobar Islands" },
  { city: "Rangpo", state: "Sikkim" },
  { city: "Ranipet", state: "Tamil Nadu" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Ratnagiri", state: "Maharashtra" },
  { city: "Rayagada", state: "Odisha" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Rewari", state: "Haryana" },
  { city: "Rishikesh", state: "Uttarakhand" },
  { city: "Robertsonpet", state: "Karnataka" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Roorkee", state: "Uttarakhand" },
  { city: "Rourkela", state: "Odisha" },
  { city: "Rudraprayag", state: "Uttarakhand" },
  { city: "Rudrapur", state: "Uttarakhand" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Saiha", state: "Mizoram" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Samastipur", state: "Bihar" },
  { city: "Sambalpur", state: "Odisha" },
  { city: "Sambhal", state: "Uttar Pradesh" },
  { city: "Sanand", state: "Gujarat" },
  { city: "Sangamner", state: "Maharashtra" },
  { city: "Sangareddy", state: "Telangana" },
  { city: "Sangli", state: "Maharashtra" },
  { city: "Sangrur", state: "Punjab" },
  { city: "Sasaram", state: "Bihar" },
  { city: "Satara", state: "Maharashtra" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Sawai Madhopur", state: "Rajasthan" },
  { city: "Secunderabad", state: "Telangana" },
  { city: "Sehore", state: "Madhya Pradesh" },
  { city: "Seoni", state: "Madhya Pradesh" },
  { city: "Serampore", state: "West Bengal" },
  { city: "Serchhip", state: "Mizoram" },
  { city: "Shahjahanpur", state: "Uttar Pradesh" },
  { city: "Shajapur", state: "Madhya Pradesh" },
  { city: "Shantipur", state: "West Bengal" },
  { city: "Shillong", state: "Meghalaya" },
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Shirdi", state: "Maharashtra" },
  { city: "Shivamogga", state: "Karnataka" },
  { city: "Shivpuri", state: "Madhya Pradesh" },
  { city: "Shrirampur", state: "Maharashtra" },
  { city: "Siddipet", state: "Telangana" },
  { city: "Sihor", state: "Gujarat" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Silchar", state: "Assam" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Silvassa", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Singrauli", state: "Madhya Pradesh" },
  { city: "Sirsa", state: "Haryana" },
  { city: "Sirsi", state: "Karnataka" },
  { city: "Sitapur", state: "Uttar Pradesh" },
  { city: "Sivakasi", state: "Tamil Nadu" },
  { city: "Sivasagar", state: "Assam" },
  { city: "Siwan", state: "Bihar" },
  { city: "Solan", state: "Himachal Pradesh" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Sopore", state: "Jammu & Kashmir" },
  { city: "Sri Ganganagar", state: "Rajasthan" },
  { city: "Srikakulam", state: "Andhra Pradesh" },
  { city: "Srinagar", state: "Jammu & Kashmir" },
  { city: "Sultanpur", state: "Uttar Pradesh" },
  { city: "Surat", state: "Gujarat" },
  { city: "Surendranagar", state: "Gujarat" },
  { city: "Suryapet", state: "Telangana" },
  { city: "Tadepalligudem", state: "Andhra Pradesh" },
  { city: "Tambaram", state: "Tamil Nadu" },
  { city: "Tawang", state: "Arunachal Pradesh" },
  { city: "Tehri", state: "Uttarakhand" },
  { city: "Tenali", state: "Andhra Pradesh" },
  { city: "Tezpur", state: "Assam" },
  { city: "Thalassery", state: "Kerala" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Thanesar", state: "Haryana" },
  { city: "Thanjavur", state: "Tamil Nadu" },
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Thoothukudi", state: "Tamil Nadu" },
  { city: "Thoubal", state: "Manipur" },
  { city: "Thrissur", state: "Kerala" },
  { city: "Tinsukia", state: "Assam" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Tirupati", state: "Andhra Pradesh" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Tirur", state: "Kerala" },
  { city: "Tiruvannamalai", state: "Tamil Nadu" },
  { city: "Tonk", state: "Rajasthan" },
  { city: "Tuensang", state: "Nagaland" },
  { city: "Tumakuru", state: "Karnataka" },
  { city: "Tura", state: "Meghalaya" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Udaipur", state: "Tripura" },
  { city: "Udhagamandalam", state: "Tamil Nadu" },
  { city: "Udhampur", state: "Jammu & Kashmir" },
  { city: "Udupi", state: "Karnataka" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Ukhrul", state: "Manipur" },
  { city: "Ulhasnagar", state: "Maharashtra" },
  { city: "Una", state: "Himachal Pradesh" },
  { city: "Unjha", state: "Gujarat" },
  { city: "Unnao", state: "Uttar Pradesh" },
  { city: "Upleta", state: "Gujarat" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Vallabh Vidyanagar", state: "Gujarat" },
  { city: "Valsad", state: "Gujarat" },
  { city: "Vapi", state: "Gujarat" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Vasai-Virar", state: "Maharashtra" },
  { city: "Vasco da Gama", state: "Goa" },
  { city: "Vellore", state: "Tamil Nadu" },
  { city: "Veraval", state: "Gujarat" },
  { city: "Vidisha", state: "Madhya Pradesh" },
  { city: "Vijapur", state: "Gujarat" },
  { city: "Vijayapura", state: "Karnataka" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Villupuram", state: "Tamil Nadu" },
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Visnagar", state: "Gujarat" },
  { city: "Vizianagaram", state: "Andhra Pradesh" },
  { city: "Vrindavan", state: "Uttar Pradesh" },
  { city: "Wai", state: "Maharashtra" },
  { city: "Wankaner", state: "Gujarat" },
  { city: "Warangal", state: "Telangana" },
  { city: "Wardha", state: "Maharashtra" },
  { city: "Washim", state: "Maharashtra" },
  { city: "Williamnagar", state: "Meghalaya" },
  { city: "Wokha", state: "Nagaland" },
  { city: "Yamunanagar", state: "Haryana" },
  { city: "Yanam", state: "Puducherry" },
  { city: "Yavatmal", state: "Maharashtra" },
  { city: "Zirakpur", state: "Punjab" },
  { city: "Ziro", state: "Arunachal Pradesh" },
  { city: "Zunheboto", state: "Nagaland" },
]
