// A bundled offline dataset of world countries with their E.164 dial codes, for
// the country-code picker in the PhoneInput component. No network or API call:
// the list ships with the app so the picker works offline. Dial codes are the
// country calling code without the leading '+'. Some codes are shared (the NANP
// countries all use '1'), so each entry carries its own iso/flag. `nationalLength`
// is set only where the national-number digit length is reliably fixed.
// Sorted by name; consumers float the default (India) to the top in the UI.

export interface Country {
  iso: string // ISO 3166-1 alpha-2, uppercase, e.g. 'IN'
  name: string // common English name, e.g. 'India'
  dialCode: string // E.164 country calling code WITHOUT +, e.g. '91'
  flag: string // emoji flag, e.g. '🇮🇳'
  nationalLength?: number | number[] // expected national-number digit length(s) where well-known
}

export const COUNTRIES: Country[] = [
  { iso: 'AF', name: 'Afghanistan', dialCode: '93', flag: '🇦🇫' },
  { iso: 'AX', name: 'Åland Islands', dialCode: '358', flag: '🇦🇽' },
  { iso: 'AL', name: 'Albania', dialCode: '355', flag: '🇦🇱' },
  { iso: 'DZ', name: 'Algeria', dialCode: '213', flag: '🇩🇿' },
  { iso: 'AS', name: 'American Samoa', dialCode: '1', flag: '🇦🇸', nationalLength: 10 },
  { iso: 'AD', name: 'Andorra', dialCode: '376', flag: '🇦🇩' },
  { iso: 'AO', name: 'Angola', dialCode: '244', flag: '🇦🇴' },
  { iso: 'AI', name: 'Anguilla', dialCode: '1', flag: '🇦🇮', nationalLength: 10 },
  { iso: 'AQ', name: 'Antarctica', dialCode: '672', flag: '🇦🇶' },
  { iso: 'AG', name: 'Antigua and Barbuda', dialCode: '1', flag: '🇦🇬', nationalLength: 10 },
  { iso: 'AR', name: 'Argentina', dialCode: '54', flag: '🇦🇷' },
  { iso: 'AM', name: 'Armenia', dialCode: '374', flag: '🇦🇲' },
  { iso: 'AW', name: 'Aruba', dialCode: '297', flag: '🇦🇼' },
  { iso: 'AU', name: 'Australia', dialCode: '61', flag: '🇦🇺', nationalLength: 9 },
  { iso: 'AT', name: 'Austria', dialCode: '43', flag: '🇦🇹' },
  { iso: 'AZ', name: 'Azerbaijan', dialCode: '994', flag: '🇦🇿' },
  { iso: 'BS', name: 'Bahamas', dialCode: '1', flag: '🇧🇸', nationalLength: 10 },
  { iso: 'BH', name: 'Bahrain', dialCode: '973', flag: '🇧🇭', nationalLength: 8 },
  { iso: 'BD', name: 'Bangladesh', dialCode: '880', flag: '🇧🇩', nationalLength: 10 },
  { iso: 'BB', name: 'Barbados', dialCode: '1', flag: '🇧🇧', nationalLength: 10 },
  { iso: 'BY', name: 'Belarus', dialCode: '375', flag: '🇧🇾' },
  { iso: 'BE', name: 'Belgium', dialCode: '32', flag: '🇧🇪' },
  { iso: 'BZ', name: 'Belize', dialCode: '501', flag: '🇧🇿' },
  { iso: 'BJ', name: 'Benin', dialCode: '229', flag: '🇧🇯' },
  { iso: 'BM', name: 'Bermuda', dialCode: '1', flag: '🇧🇲', nationalLength: 10 },
  { iso: 'BT', name: 'Bhutan', dialCode: '975', flag: '🇧🇹' },
  { iso: 'BO', name: 'Bolivia', dialCode: '591', flag: '🇧🇴' },
  { iso: 'BQ', name: 'Bonaire, Sint Eustatius and Saba', dialCode: '599', flag: '🇧🇶' },
  { iso: 'BA', name: 'Bosnia and Herzegovina', dialCode: '387', flag: '🇧🇦' },
  { iso: 'BW', name: 'Botswana', dialCode: '267', flag: '🇧🇼' },
  { iso: 'BR', name: 'Brazil', dialCode: '55', flag: '🇧🇷' },
  { iso: 'IO', name: 'British Indian Ocean Territory', dialCode: '246', flag: '🇮🇴' },
  { iso: 'VG', name: 'British Virgin Islands', dialCode: '1', flag: '🇻🇬', nationalLength: 10 },
  { iso: 'BN', name: 'Brunei', dialCode: '673', flag: '🇧🇳' },
  { iso: 'BG', name: 'Bulgaria', dialCode: '359', flag: '🇧🇬' },
  { iso: 'BF', name: 'Burkina Faso', dialCode: '226', flag: '🇧🇫' },
  { iso: 'BI', name: 'Burundi', dialCode: '257', flag: '🇧🇮' },
  { iso: 'CV', name: 'Cabo Verde', dialCode: '238', flag: '🇨🇻' },
  { iso: 'KH', name: 'Cambodia', dialCode: '855', flag: '🇰🇭' },
  { iso: 'CM', name: 'Cameroon', dialCode: '237', flag: '🇨🇲' },
  { iso: 'CA', name: 'Canada', dialCode: '1', flag: '🇨🇦', nationalLength: 10 },
  { iso: 'KY', name: 'Cayman Islands', dialCode: '1', flag: '🇰🇾', nationalLength: 10 },
  { iso: 'CF', name: 'Central African Republic', dialCode: '236', flag: '🇨🇫' },
  { iso: 'TD', name: 'Chad', dialCode: '235', flag: '🇹🇩' },
  { iso: 'CL', name: 'Chile', dialCode: '56', flag: '🇨🇱' },
  { iso: 'CN', name: 'China', dialCode: '86', flag: '🇨🇳', nationalLength: 11 },
  { iso: 'CX', name: 'Christmas Island', dialCode: '61', flag: '🇨🇽' },
  { iso: 'CC', name: 'Cocos (Keeling) Islands', dialCode: '61', flag: '🇨🇨' },
  { iso: 'CO', name: 'Colombia', dialCode: '57', flag: '🇨🇴' },
  { iso: 'KM', name: 'Comoros', dialCode: '269', flag: '🇰🇲' },
  { iso: 'CG', name: 'Congo', dialCode: '242', flag: '🇨🇬' },
  { iso: 'CD', name: 'Congo (DRC)', dialCode: '243', flag: '🇨🇩' },
  { iso: 'CK', name: 'Cook Islands', dialCode: '682', flag: '🇨🇰' },
  { iso: 'CR', name: 'Costa Rica', dialCode: '506', flag: '🇨🇷' },
  { iso: 'CI', name: "Côte d'Ivoire", dialCode: '225', flag: '🇨🇮' },
  { iso: 'HR', name: 'Croatia', dialCode: '385', flag: '🇭🇷' },
  { iso: 'CU', name: 'Cuba', dialCode: '53', flag: '🇨🇺' },
  { iso: 'CW', name: 'Curaçao', dialCode: '599', flag: '🇨🇼' },
  { iso: 'CY', name: 'Cyprus', dialCode: '357', flag: '🇨🇾' },
  { iso: 'CZ', name: 'Czechia', dialCode: '420', flag: '🇨🇿' },
  { iso: 'DK', name: 'Denmark', dialCode: '45', flag: '🇩🇰', nationalLength: 8 },
  { iso: 'DJ', name: 'Djibouti', dialCode: '253', flag: '🇩🇯' },
  { iso: 'DM', name: 'Dominica', dialCode: '1', flag: '🇩🇲', nationalLength: 10 },
  { iso: 'DO', name: 'Dominican Republic', dialCode: '1', flag: '🇩🇴', nationalLength: 10 },
  { iso: 'EC', name: 'Ecuador', dialCode: '593', flag: '🇪🇨' },
  { iso: 'EG', name: 'Egypt', dialCode: '20', flag: '🇪🇬' },
  { iso: 'SV', name: 'El Salvador', dialCode: '503', flag: '🇸🇻' },
  { iso: 'GQ', name: 'Equatorial Guinea', dialCode: '240', flag: '🇬🇶' },
  { iso: 'ER', name: 'Eritrea', dialCode: '291', flag: '🇪🇷' },
  { iso: 'EE', name: 'Estonia', dialCode: '372', flag: '🇪🇪' },
  { iso: 'SZ', name: 'Eswatini', dialCode: '268', flag: '🇸🇿' },
  { iso: 'ET', name: 'Ethiopia', dialCode: '251', flag: '🇪🇹' },
  { iso: 'FK', name: 'Falkland Islands', dialCode: '500', flag: '🇫🇰' },
  { iso: 'FO', name: 'Faroe Islands', dialCode: '298', flag: '🇫🇴' },
  { iso: 'FJ', name: 'Fiji', dialCode: '679', flag: '🇫🇯' },
  { iso: 'FI', name: 'Finland', dialCode: '358', flag: '🇫🇮' },
  { iso: 'FR', name: 'France', dialCode: '33', flag: '🇫🇷', nationalLength: 9 },
  { iso: 'GF', name: 'French Guiana', dialCode: '594', flag: '🇬🇫' },
  { iso: 'PF', name: 'French Polynesia', dialCode: '689', flag: '🇵🇫' },
  { iso: 'GA', name: 'Gabon', dialCode: '241', flag: '🇬🇦' },
  { iso: 'GM', name: 'Gambia', dialCode: '220', flag: '🇬🇲' },
  { iso: 'GE', name: 'Georgia', dialCode: '995', flag: '🇬🇪' },
  { iso: 'DE', name: 'Germany', dialCode: '49', flag: '🇩🇪' },
  { iso: 'GH', name: 'Ghana', dialCode: '233', flag: '🇬🇭' },
  { iso: 'GI', name: 'Gibraltar', dialCode: '350', flag: '🇬🇮' },
  { iso: 'GR', name: 'Greece', dialCode: '30', flag: '🇬🇷' },
  { iso: 'GL', name: 'Greenland', dialCode: '299', flag: '🇬🇱' },
  { iso: 'GD', name: 'Grenada', dialCode: '1', flag: '🇬🇩', nationalLength: 10 },
  { iso: 'GP', name: 'Guadeloupe', dialCode: '590', flag: '🇬🇵' },
  { iso: 'GU', name: 'Guam', dialCode: '1', flag: '🇬🇺', nationalLength: 10 },
  { iso: 'GT', name: 'Guatemala', dialCode: '502', flag: '🇬🇹' },
  { iso: 'GG', name: 'Guernsey', dialCode: '44', flag: '🇬🇬' },
  { iso: 'GN', name: 'Guinea', dialCode: '224', flag: '🇬🇳' },
  { iso: 'GW', name: 'Guinea-Bissau', dialCode: '245', flag: '🇬🇼' },
  { iso: 'GY', name: 'Guyana', dialCode: '592', flag: '🇬🇾' },
  { iso: 'HT', name: 'Haiti', dialCode: '509', flag: '🇭🇹' },
  { iso: 'HN', name: 'Honduras', dialCode: '504', flag: '🇭🇳' },
  { iso: 'HK', name: 'Hong Kong', dialCode: '852', flag: '🇭🇰', nationalLength: 8 },
  { iso: 'HU', name: 'Hungary', dialCode: '36', flag: '🇭🇺' },
  { iso: 'IS', name: 'Iceland', dialCode: '354', flag: '🇮🇸' },
  { iso: 'IN', name: 'India', dialCode: '91', flag: '🇮🇳', nationalLength: 10 },
  { iso: 'ID', name: 'Indonesia', dialCode: '62', flag: '🇮🇩' },
  { iso: 'IR', name: 'Iran', dialCode: '98', flag: '🇮🇷' },
  { iso: 'IQ', name: 'Iraq', dialCode: '964', flag: '🇮🇶' },
  { iso: 'IE', name: 'Ireland', dialCode: '353', flag: '🇮🇪' },
  { iso: 'IM', name: 'Isle of Man', dialCode: '44', flag: '🇮🇲' },
  { iso: 'IL', name: 'Israel', dialCode: '972', flag: '🇮🇱' },
  { iso: 'IT', name: 'Italy', dialCode: '39', flag: '🇮🇹' },
  { iso: 'JM', name: 'Jamaica', dialCode: '1', flag: '🇯🇲', nationalLength: 10 },
  { iso: 'JP', name: 'Japan', dialCode: '81', flag: '🇯🇵' },
  { iso: 'JE', name: 'Jersey', dialCode: '44', flag: '🇯🇪' },
  { iso: 'JO', name: 'Jordan', dialCode: '962', flag: '🇯🇴' },
  { iso: 'KZ', name: 'Kazakhstan', dialCode: '7', flag: '🇰🇿' },
  { iso: 'KE', name: 'Kenya', dialCode: '254', flag: '🇰🇪' },
  { iso: 'KI', name: 'Kiribati', dialCode: '686', flag: '🇰🇮' },
  { iso: 'XK', name: 'Kosovo', dialCode: '383', flag: '🇽🇰' },
  { iso: 'KW', name: 'Kuwait', dialCode: '965', flag: '🇰🇼', nationalLength: 8 },
  { iso: 'KG', name: 'Kyrgyzstan', dialCode: '996', flag: '🇰🇬' },
  { iso: 'LA', name: 'Laos', dialCode: '856', flag: '🇱🇦' },
  { iso: 'LV', name: 'Latvia', dialCode: '371', flag: '🇱🇻' },
  { iso: 'LB', name: 'Lebanon', dialCode: '961', flag: '🇱🇧' },
  { iso: 'LS', name: 'Lesotho', dialCode: '266', flag: '🇱🇸' },
  { iso: 'LR', name: 'Liberia', dialCode: '231', flag: '🇱🇷' },
  { iso: 'LY', name: 'Libya', dialCode: '218', flag: '🇱🇾' },
  { iso: 'LI', name: 'Liechtenstein', dialCode: '423', flag: '🇱🇮' },
  { iso: 'LT', name: 'Lithuania', dialCode: '370', flag: '🇱🇹' },
  { iso: 'LU', name: 'Luxembourg', dialCode: '352', flag: '🇱🇺' },
  { iso: 'MO', name: 'Macao', dialCode: '853', flag: '🇲🇴', nationalLength: 8 },
  { iso: 'MG', name: 'Madagascar', dialCode: '261', flag: '🇲🇬' },
  { iso: 'MW', name: 'Malawi', dialCode: '265', flag: '🇲🇼' },
  { iso: 'MY', name: 'Malaysia', dialCode: '60', flag: '🇲🇾' },
  { iso: 'MV', name: 'Maldives', dialCode: '960', flag: '🇲🇻', nationalLength: 7 },
  { iso: 'ML', name: 'Mali', dialCode: '223', flag: '🇲🇱' },
  { iso: 'MT', name: 'Malta', dialCode: '356', flag: '🇲🇹', nationalLength: 8 },
  { iso: 'MH', name: 'Marshall Islands', dialCode: '692', flag: '🇲🇭' },
  { iso: 'MQ', name: 'Martinique', dialCode: '596', flag: '🇲🇶' },
  { iso: 'MR', name: 'Mauritania', dialCode: '222', flag: '🇲🇷' },
  { iso: 'MU', name: 'Mauritius', dialCode: '230', flag: '🇲🇺' },
  { iso: 'YT', name: 'Mayotte', dialCode: '262', flag: '🇾🇹' },
  { iso: 'MX', name: 'Mexico', dialCode: '52', flag: '🇲🇽' },
  { iso: 'FM', name: 'Micronesia', dialCode: '691', flag: '🇫🇲' },
  { iso: 'MD', name: 'Moldova', dialCode: '373', flag: '🇲🇩' },
  { iso: 'MC', name: 'Monaco', dialCode: '377', flag: '🇲🇨' },
  { iso: 'MN', name: 'Mongolia', dialCode: '976', flag: '🇲🇳' },
  { iso: 'ME', name: 'Montenegro', dialCode: '382', flag: '🇲🇪' },
  { iso: 'MS', name: 'Montserrat', dialCode: '1', flag: '🇲🇸', nationalLength: 10 },
  { iso: 'MA', name: 'Morocco', dialCode: '212', flag: '🇲🇦' },
  { iso: 'MZ', name: 'Mozambique', dialCode: '258', flag: '🇲🇿' },
  { iso: 'MM', name: 'Myanmar', dialCode: '95', flag: '🇲🇲' },
  { iso: 'NA', name: 'Namibia', dialCode: '264', flag: '🇳🇦' },
  { iso: 'NR', name: 'Nauru', dialCode: '674', flag: '🇳🇷' },
  { iso: 'NP', name: 'Nepal', dialCode: '977', flag: '🇳🇵', nationalLength: 10 },
  { iso: 'NL', name: 'Netherlands', dialCode: '31', flag: '🇳🇱' },
  { iso: 'NC', name: 'New Caledonia', dialCode: '687', flag: '🇳🇨' },
  { iso: 'NZ', name: 'New Zealand', dialCode: '64', flag: '🇳🇿' },
  { iso: 'NI', name: 'Nicaragua', dialCode: '505', flag: '🇳🇮' },
  { iso: 'NE', name: 'Niger', dialCode: '227', flag: '🇳🇪' },
  { iso: 'NG', name: 'Nigeria', dialCode: '234', flag: '🇳🇬' },
  { iso: 'NU', name: 'Niue', dialCode: '683', flag: '🇳🇺' },
  { iso: 'NF', name: 'Norfolk Island', dialCode: '672', flag: '🇳🇫' },
  { iso: 'KP', name: 'North Korea', dialCode: '850', flag: '🇰🇵' },
  { iso: 'MK', name: 'North Macedonia', dialCode: '389', flag: '🇲🇰' },
  { iso: 'MP', name: 'Northern Mariana Islands', dialCode: '1', flag: '🇲🇵', nationalLength: 10 },
  { iso: 'NO', name: 'Norway', dialCode: '47', flag: '🇳🇴', nationalLength: 8 },
  { iso: 'OM', name: 'Oman', dialCode: '968', flag: '🇴🇲', nationalLength: 8 },
  { iso: 'PK', name: 'Pakistan', dialCode: '92', flag: '🇵🇰', nationalLength: 10 },
  { iso: 'PW', name: 'Palau', dialCode: '680', flag: '🇵🇼' },
  { iso: 'PS', name: 'Palestine', dialCode: '970', flag: '🇵🇸' },
  { iso: 'PA', name: 'Panama', dialCode: '507', flag: '🇵🇦' },
  { iso: 'PG', name: 'Papua New Guinea', dialCode: '675', flag: '🇵🇬' },
  { iso: 'PY', name: 'Paraguay', dialCode: '595', flag: '🇵🇾' },
  { iso: 'PE', name: 'Peru', dialCode: '51', flag: '🇵🇪' },
  { iso: 'PH', name: 'Philippines', dialCode: '63', flag: '🇵🇭', nationalLength: 10 },
  { iso: 'PN', name: 'Pitcairn Islands', dialCode: '64', flag: '🇵🇳' },
  { iso: 'PL', name: 'Poland', dialCode: '48', flag: '🇵🇱', nationalLength: 9 },
  { iso: 'PT', name: 'Portugal', dialCode: '351', flag: '🇵🇹', nationalLength: 9 },
  { iso: 'PR', name: 'Puerto Rico', dialCode: '1', flag: '🇵🇷', nationalLength: 10 },
  { iso: 'QA', name: 'Qatar', dialCode: '974', flag: '🇶🇦', nationalLength: 8 },
  { iso: 'RE', name: 'Réunion', dialCode: '262', flag: '🇷🇪' },
  { iso: 'RO', name: 'Romania', dialCode: '40', flag: '🇷🇴' },
  { iso: 'RU', name: 'Russia', dialCode: '7', flag: '🇷🇺', nationalLength: 10 },
  { iso: 'RW', name: 'Rwanda', dialCode: '250', flag: '🇷🇼' },
  { iso: 'BL', name: 'Saint Barthélemy', dialCode: '590', flag: '🇧🇱' },
  { iso: 'SH', name: 'Saint Helena', dialCode: '290', flag: '🇸🇭' },
  { iso: 'KN', name: 'Saint Kitts and Nevis', dialCode: '1', flag: '🇰🇳', nationalLength: 10 },
  { iso: 'LC', name: 'Saint Lucia', dialCode: '1', flag: '🇱🇨', nationalLength: 10 },
  { iso: 'MF', name: 'Saint Martin', dialCode: '590', flag: '🇲🇫' },
  { iso: 'PM', name: 'Saint Pierre and Miquelon', dialCode: '508', flag: '🇵🇲' },
  { iso: 'VC', name: 'Saint Vincent and the Grenadines', dialCode: '1', flag: '🇻🇨', nationalLength: 10 },
  { iso: 'WS', name: 'Samoa', dialCode: '685', flag: '🇼🇸' },
  { iso: 'SM', name: 'San Marino', dialCode: '378', flag: '🇸🇲' },
  { iso: 'ST', name: 'Sao Tome and Principe', dialCode: '239', flag: '🇸🇹' },
  { iso: 'SA', name: 'Saudi Arabia', dialCode: '966', flag: '🇸🇦', nationalLength: 9 },
  { iso: 'SN', name: 'Senegal', dialCode: '221', flag: '🇸🇳' },
  { iso: 'RS', name: 'Serbia', dialCode: '381', flag: '🇷🇸' },
  { iso: 'SC', name: 'Seychelles', dialCode: '248', flag: '🇸🇨' },
  { iso: 'SL', name: 'Sierra Leone', dialCode: '232', flag: '🇸🇱' },
  { iso: 'SG', name: 'Singapore', dialCode: '65', flag: '🇸🇬', nationalLength: 8 },
  { iso: 'SX', name: 'Sint Maarten', dialCode: '1', flag: '🇸🇽', nationalLength: 10 },
  { iso: 'SK', name: 'Slovakia', dialCode: '421', flag: '🇸🇰' },
  { iso: 'SI', name: 'Slovenia', dialCode: '386', flag: '🇸🇮' },
  { iso: 'SB', name: 'Solomon Islands', dialCode: '677', flag: '🇸🇧' },
  { iso: 'SO', name: 'Somalia', dialCode: '252', flag: '🇸🇴' },
  { iso: 'ZA', name: 'South Africa', dialCode: '27', flag: '🇿🇦', nationalLength: 9 },
  { iso: 'KR', name: 'South Korea', dialCode: '82', flag: '🇰🇷' },
  { iso: 'SS', name: 'South Sudan', dialCode: '211', flag: '🇸🇸' },
  { iso: 'ES', name: 'Spain', dialCode: '34', flag: '🇪🇸', nationalLength: 9 },
  { iso: 'LK', name: 'Sri Lanka', dialCode: '94', flag: '🇱🇰', nationalLength: 9 },
  { iso: 'SD', name: 'Sudan', dialCode: '249', flag: '🇸🇩' },
  { iso: 'SR', name: 'Suriname', dialCode: '597', flag: '🇸🇷' },
  { iso: 'SJ', name: 'Svalbard and Jan Mayen', dialCode: '47', flag: '🇸🇯' },
  { iso: 'SE', name: 'Sweden', dialCode: '46', flag: '🇸🇪' },
  { iso: 'CH', name: 'Switzerland', dialCode: '41', flag: '🇨🇭', nationalLength: 9 },
  { iso: 'SY', name: 'Syria', dialCode: '963', flag: '🇸🇾' },
  { iso: 'TW', name: 'Taiwan', dialCode: '886', flag: '🇹🇼' },
  { iso: 'TJ', name: 'Tajikistan', dialCode: '992', flag: '🇹🇯' },
  { iso: 'TZ', name: 'Tanzania', dialCode: '255', flag: '🇹🇿' },
  { iso: 'TH', name: 'Thailand', dialCode: '66', flag: '🇹🇭', nationalLength: 9 },
  { iso: 'TL', name: 'Timor-Leste', dialCode: '670', flag: '🇹🇱' },
  { iso: 'TG', name: 'Togo', dialCode: '228', flag: '🇹🇬' },
  { iso: 'TK', name: 'Tokelau', dialCode: '690', flag: '🇹🇰' },
  { iso: 'TO', name: 'Tonga', dialCode: '676', flag: '🇹🇴' },
  { iso: 'TT', name: 'Trinidad and Tobago', dialCode: '1', flag: '🇹🇹', nationalLength: 10 },
  { iso: 'TN', name: 'Tunisia', dialCode: '216', flag: '🇹🇳', nationalLength: 8 },
  { iso: 'TR', name: 'Turkey', dialCode: '90', flag: '🇹🇷', nationalLength: 10 },
  { iso: 'TM', name: 'Turkmenistan', dialCode: '993', flag: '🇹🇲' },
  { iso: 'TC', name: 'Turks and Caicos Islands', dialCode: '1', flag: '🇹🇨', nationalLength: 10 },
  { iso: 'TV', name: 'Tuvalu', dialCode: '688', flag: '🇹🇻' },
  { iso: 'VI', name: 'U.S. Virgin Islands', dialCode: '1', flag: '🇻🇮', nationalLength: 10 },
  { iso: 'UG', name: 'Uganda', dialCode: '256', flag: '🇺🇬' },
  { iso: 'UA', name: 'Ukraine', dialCode: '380', flag: '🇺🇦', nationalLength: 9 },
  { iso: 'AE', name: 'United Arab Emirates', dialCode: '971', flag: '🇦🇪', nationalLength: 9 },
  { iso: 'GB', name: 'United Kingdom', dialCode: '44', flag: '🇬🇧', nationalLength: 10 },
  { iso: 'US', name: 'United States', dialCode: '1', flag: '🇺🇸', nationalLength: 10 },
  { iso: 'UY', name: 'Uruguay', dialCode: '598', flag: '🇺🇾' },
  { iso: 'UZ', name: 'Uzbekistan', dialCode: '998', flag: '🇺🇿' },
  { iso: 'VU', name: 'Vanuatu', dialCode: '678', flag: '🇻🇺' },
  { iso: 'VA', name: 'Vatican City', dialCode: '39', flag: '🇻🇦' },
  { iso: 'VE', name: 'Venezuela', dialCode: '58', flag: '🇻🇪' },
  { iso: 'VN', name: 'Vietnam', dialCode: '84', flag: '🇻🇳', nationalLength: 9 },
  { iso: 'WF', name: 'Wallis and Futuna', dialCode: '681', flag: '🇼🇫' },
  { iso: 'EH', name: 'Western Sahara', dialCode: '212', flag: '🇪🇭' },
  { iso: 'YE', name: 'Yemen', dialCode: '967', flag: '🇾🇪' },
  { iso: 'ZM', name: 'Zambia', dialCode: '260', flag: '🇿🇲' },
  { iso: 'ZW', name: 'Zimbabwe', dialCode: '263', flag: '🇿🇼' },
]

export const DEFAULT_COUNTRY_ISO = 'IN'
