// All user-facing copy lives here (i18n-ready) per SPEC.md Code Style.
export const strings = {
  appName: 'Vinayak Mandal',
  appTagline: 'Digital Vargani & Fund Management System',
  home: {
    placeholder: 'App shell is up. Features arrive in later tasks.',
  },
  auth: {
    loginTitle: 'Admin Login',
    emailLabel: 'Email address',
    sendLink: 'Send magic link',
    sending: 'Sending…',
    checkEmail: 'Check your email for a login link.',
    loading: 'Loading…',
    inviteInvalid: 'This invite link is invalid or has already been used.',
  },
  admin: {
    dashboardTitle: 'Admin Dashboard',
    dashboardPlaceholder: 'Dashboard content arrives in a later task.',
    volunteersLink: 'Manage volunteers',
    settingsLink: 'Mandal settings',
    expensesLink: 'Expenses',
  },
  mandalConfig: {
    title: 'Mandal Settings',
    nameLabel: 'Mandal name',
    logoLabel: 'Logo',
    signatureLabel: "President's signature",
    upiVpaLabel: 'UPI VPA',
    upiQrLabel: 'UPI QR code',
    categoriesLabel: 'Expense categories',
    addCategoryPlaceholder: 'Add a category',
    addCategory: 'Add',
    removeCategory: 'Remove category',
    bankOpeningLabel: 'Bank opening balance (₹)',
    uploading: 'Uploading…',
    saveButton: 'Save settings',
    saving: 'Saving…',
    saved: 'Settings saved.',
  },
  volunteers: {
    title: 'Volunteers',
    nameLabel: 'Name',
    phoneLabel: 'Phone (optional)',
    addButton: 'Add volunteer',
    adding: 'Adding…',
    empty: 'No volunteers yet.',
    pending: 'Pending',
    active: 'Active',
    copyLink: 'Copy invite link',
    copied: 'Copied!',
  },
  collection: {
    title: 'Collect Donation',
    donorNameLabel: 'Donor Name',
    donorPhoneLabel: 'Phone',
    amountLabel: 'Amount (₹)',
    modeLabel: 'Mode',
    modeCash: 'Cash',
    modeUpi: 'UPI',
    modeBank: 'Bank',
    submitButton: 'Record Donation',
    submitting: 'Recording…',
    successPrefix: 'Receipt #',
    nextDonation: 'Ready for the next donation.',
    sendReceiptButton: 'Send Receipt',
    pendingSendLink: 'Pending sends',
    expensesLink: 'Expenses',
    savedOffline: "Saved — will send once you're back online.",
    // Kept short (SMS length matters). {amountRupees} is a plain number
    // (no thousands separator, no repeated ₹) so the message stays short.
    smsMessage: (amountRupees: number, receiptLink: string): string =>
      `Thank you for your ₹${amountRupees} contribution. View your official receipt here: ${receiptLink}`,
    errors: {
      donorName: "Enter the donor's name.",
      donorPhone: 'Enter a valid phone number.',
      amountRupees: 'Enter an amount greater than zero.',
      mode: 'Select a payment mode.',
    },
  },
  pendingSend: {
    title: 'Pending Send',
    backLink: 'Back to collection',
    empty: 'No pending receipts to send.',
    sendButton: 'Send',
    sent: 'Sent!',
    waitingForSignal: 'Waiting for signal',
  },
  expenses: {
    title: 'Expenses',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Select a category',
    descriptionLabel: 'Description',
    amountLabel: 'Amount (₹)',
    paidFromLabel: 'Paid from',
    paidFromCash: 'Cash',
    paidFromBank: 'Bank',
    submitButton: 'Log Expense',
    submitting: 'Logging…',
    empty: 'No expenses yet.',
    paidByPrefix: 'Paid by ',
    unknownUser: 'Unknown',
    voidedPrefix: 'Voided — ',
    voidButton: 'Void',
    voidPrompt: 'Reason for voiding this expense:',
    errors: {
      category: 'Select a valid category.',
      amountRupees: 'Enter an amount greater than zero.',
      paidFrom: 'Select cash or bank.',
    },
  },
  receipt: {
    notFound: 'Receipt not found.',
    donorLabel: 'Donor',
    amountLabel: 'Amount',
    receiptNoLabel: 'Receipt No.',
    dateLabel: 'Date',
    stampCash: 'RECEIVED: CASH',
    stampOnline: 'RECEIVED: ONLINE',
    voidedBanner: 'This entry has been voided',
    voidedReasonPrefix: 'Reason: ',
    signatureLabel: 'President',
  },
}
