// All user-facing copy lives here (i18n-ready) per SPEC.md Code Style.
export const strings = {
  appName: 'Vinayak Mandal',
  appTagline: 'Digital Vargani & Fund Management System',
  home: {
    placeholder: 'App shell is up. Features arrive in later tasks.',
  },
  void: {
    button: 'Void',
    prompt: 'Reason for voiding this entry:',
  },
  auth: {
    loginTitle: 'Admin Login',
    emailLabel: 'Email address',
    sendLink: 'Send magic link',
    sending: 'Sending…',
    checkEmail: 'Check your email for a login link.',
    loading: 'Loading…',
    inviteInvalid: 'This invite link is invalid or has already been used.',
  },
  admin: {
    dashboardTitle: 'Admin Dashboard',
    volunteersLink: 'Manage volunteers',
    settingsLink: 'Mandal settings',
    expensesLink: 'Expenses',
    handoversLink: 'Handovers',
    cashInHandLink: 'Cash in hand',
    transparencyLink: 'Transparency report',
  },
  mandalConfig: {
    title: 'Mandal Settings',
    nameLabel: 'Mandal name',
    logoLabel: 'Logo',
    signatureLabel: "President's signature",
    upiVpaLabel: 'UPI VPA',
    upiQrLabel: 'UPI QR code',
    categoriesLabel: 'Expense categories',
    addCategoryPlaceholder: 'Add a category',
    addCategory: 'Add',
    removeCategory: 'Remove category',
    bankOpeningLabel: 'Bank opening balance (₹)',
    uploading: 'Uploading…',
    saveButton: 'Save settings',
    saving: 'Saving…',
    saved: 'Settings saved.',
  },
  volunteers: {
    title: 'Volunteers',
    nameLabel: 'Name',
    phoneLabel: 'Phone (optional)',
    addButton: 'Add volunteer',
    adding: 'Adding…',
    empty: 'No volunteers yet.',
    pending: 'Pending',
    active: 'Active',
    copyLink: 'Copy invite link',
    copied: 'Copied!',
  },
  collection: {
    title: 'Collect Donation',
    donorNameLabel: 'Donor Name',
    donorPhoneLabel: 'Phone',
    amountLabel: 'Amount (₹)',
    modeLabel: 'Mode',
    modeCash: 'Cash',
    modeUpi: 'UPI',
    modeBank: 'Bank',
    submitButton: 'Record Donation',
    submitting: 'Recording…',
    successPrefix: 'Receipt #',
    nextDonation: 'Ready for the next donation.',
    sendReceiptButton: 'Send Receipt',
    pendingSendLink: 'Pending sends',
    expensesLink: 'Expenses',
    handoversLink: 'Handovers',
    cashInHandLink: 'Cash in hand',
    savedOffline: "Saved — will send once you're back online.",
    // Kept short (SMS length matters). {amountRupees} is a plain number
    // (no thousands separator, no repeated ₹) so the message stays short.
    smsMessage: (amountRupees: number, receiptLink: string): string =>
      `Thank you for your ₹${amountRupees} contribution. View your official receipt here: ${receiptLink}`,
    errors: {
      donorName: "Enter the donor's name.",
      donorPhone: 'Enter a valid phone number.',
      amountRupees: 'Enter an amount greater than zero.',
      mode: 'Select a payment mode.',
    },
  },
  pendingSend: {
    title: 'Pending Send',
    backLink: 'Back to collection',
    empty: 'No pending receipts to send.',
    sendButton: 'Send',
    sent: 'Sent!',
    waitingForSignal: 'Waiting for signal',
    voidButton: 'Void',
    voidPrompt: 'Reason for voiding this donation:',
    voidedPrefix: 'Voided — ',
  },
  expenses: {
    title: 'Expenses',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Select a category',
    descriptionLabel: 'Description',
    amountLabel: 'Amount (₹)',
    paidFromLabel: 'Paid from',
    paidFromCash: 'Cash',
    paidFromBank: 'Bank',
    submitButton: 'Log Expense',
    submitting: 'Logging…',
    empty: 'No expenses yet.',
    paidByPrefix: 'Paid by ',
    unknownUser: 'Unknown',
    voidedPrefix: 'Voided — ',
    voidButton: 'Void',
    voidPrompt: 'Reason for voiding this expense:',
    errors: {
      category: 'Select a valid category.',
      amountRupees: 'Enter an amount greater than zero.',
      paidFrom: 'Select cash or bank.',
    },
  },
  handovers: {
    title: 'Handovers',
    amountLabel: 'Amount (₹)',
    receivedByLabel: 'Received by',
    receivedByPlaceholder: 'Select an admin',
    noteLabel: 'Note',
    submitButton: 'Log Handover',
    submitting: 'Logging…',
    empty: 'No handovers yet.',
    volunteerPrefix: 'From ',
    receivedByPrefix: 'To ',
    unknownUser: 'Unknown',
    voidedPrefix: 'Voided — ',
    voidButton: 'Void',
    voidPrompt: 'Reason for voiding this handover:',
    errors: {
      amountRupees: 'Enter an amount greater than zero.',
      receivedBy: 'Select who received the cash.',
    },
  },
  cashInHand: {
    title: 'Cash in Hand',
    empty: 'No active volunteers yet.',
  },
  transparency: {
    title: 'Transparency Report',
    totalCollectedLabel: 'Total Collected',
    noExpenses: 'No expenses recorded yet.',
    otherCategory: 'Other',
    notPublished: 'The transparency report has not been published yet.',
    publishButton: 'Publish',
    unpublishButton: 'Unpublish',
    publishedStatus: 'Visible to the public.',
    unpublishedStatus: 'Not visible to the public yet.',
  },
  ledger: {
    totalCollectedLabel: 'Total Collected',
    totalExpensesLabel: 'Total Expenses',
    netBalanceLabel: 'Net Balance',
    balanced: 'Books balanced',
    discrepancyPrefix: 'Discrepancy: ',
  },
  receipt: {
    notFound: 'Receipt not found.',
    donorLabel: 'Donor',
    amountLabel: 'Amount',
    receiptNoLabel: 'Receipt No.',
    dateLabel: 'Date',
    stampCash: 'RECEIVED: CASH',
    stampOnline: 'RECEIVED: ONLINE',
    voidedBanner: 'This entry has been voided',
    voidedReasonPrefix: 'Reason: ',
    signatureLabel: 'President',
  },
}
