// All user-facing copy lives here (i18n-ready) per SPEC.md Code Style.
export const strings = {
  appName: 'Digital Vargani',
  appTagline: 'Digital Vargani & Fund Management System',
  app: {
    signOut: 'Sign out',
    // Only donation collection has an offline queue; expenses/handovers write
    // straight to the server, so set that expectation up front (audit #10).
    onlineOnlyHint: 'Needs a connection — this saves online now, it does not queue offline like collecting donations.',
    // v4: PhoneInput country picker
    countrySearchPlaceholder: 'Search country or code…',
  },
  void: {
    button: 'Void',
    prompt: 'Reason (optional)',
    body: "It will be removed from your mandal's totals, and this can't be undone.",
    cancel: 'Cancel',
    reasonPlaceholder: 'e.g. entered twice',
    defaultReason: 'Removed by mistake',
  },
  auth: {
    loginTitle: 'Welcome back',
    loginSubtitle: 'Sign in to your mandal — or create a new one.',
    emailLabel: 'Email address',
    emailPlaceholder: 'you@example.com',
    sendLink: 'Email me a login link',
    sending: 'Sending…',
    checkEmail: 'Check your email',
    checkEmailHelp: 'Open the sign-in link on this device to continue.',
    checkEmailSentTo: 'We sent a sign-in link to',
    continueWithGoogle: 'Continue with Google',
    startingGoogle: 'Opening Google…',
    googleError: 'Could not start Google sign-in. Please try again.',
    or: 'or',
    loading: 'Loading…',
    inviteInvalid: 'This invite link is invalid or has already been used.',
    inviteInvalidHelp: 'Ask your mandal admin to resend your invite link on WhatsApp, then open the new one.',
    inviteSwitchTitle: "You're already signed in",
    inviteSwitchBody: 'Opening this invite will sign you out and switch to it. Continue?',
    inviteSwitchContinue: 'Continue and switch',
    inviteSwitchCancel: 'Stay signed in',
    volunteerHint: 'Collecting for a mandal? Open the invite link your admin shared — volunteers need no login.',
    retryTitle: "Couldn't load your account",
    retryBody: 'We reached the server but your account details did not load. Check your connection and try again.',
    retryButton: 'Try again',
    newHereTitle: 'First time?',
    newHere: "Sign in above with Google or email, and we'll walk you through creating your mandal.",
    backToLogin: 'Use a different email',
  },
  // The /signup fork: someone authenticated but with no mandal yet picks
  // between founding one and joining an existing one as an invited volunteer.
  signupChoice: {
    title: 'Welcome! What brings you here?',
    createTitle: 'Create a new mandal',
    createBody: "Start fresh — you'll be its first admin and can invite your team.",
    createCta: 'Create a mandal →',
    invitedTitle: 'I was invited to a mandal',
    invitedBody: 'Volunteers and admins join through the invite link their mandal shares on WhatsApp — no login needed. Open that link on this phone to continue.',
    invitedHint: "Don't have it? Ask your mandal admin to send (or resend) your invite link.",
    back: '← Back',
  },
  signup: {
    title: 'Start your mandal',
    intro: 'A few details and you become its first admin. You can invite your team and fine-tune everything next.',
    stepHint: 'Takes about a minute',
    mandalNameLabel: 'Mandal name',
    mandalNamePlaceholder: 'e.g. Vinayak Yuvak Mandal',
    adminNameLabel: 'Your name',
    adminNamePlaceholder: 'The first admin — you',
    stateLabel: 'State',
    statePlaceholder: 'Select your state',
    addressLabel: 'Address',
    optional: 'optional',
    addressPlaceholder: 'Area, landmark, city…',
    addressHelp: 'Shown on receipts and your public report. You can add or change it later.',
    slugLabel: 'Public link',
    slugHelp: 'Leave blank and we pick one from your mandal name.',
    slugPreviewPrefix: '/transparency/',
    submit: 'Create my mandal',
    submitting: 'Creating…',
    // F7: city typeahead replaces the bare state dropdown (fills both)
    cityLabel: 'City',
    cityPlaceholder: 'Start typing your city…',
    cityHelp: 'Pick your city — we fill in the state.',
    cityNotListed: "Can't find it? Type your city and choose “Use as typed”.",
    cityUseAsTyped: 'Use as typed',
  },
  admin: {
    dashboardTitle: 'Admin Dashboard',
    dashboardSubtitle: 'Your mandal at a glance',
    volunteersLink: 'Manage volunteers',
    settingsLink: 'Mandal settings',
    expensesLink: 'Expenses',
    handoversLink: 'Handovers',
    cashInHandLink: 'Cash in hand',
    transparencyLink: 'Transparency report',
    collectionsLink: 'All collections',
    collectDonationLink: 'Collect donation',
    adminsLink: 'Manage admins',
    donorsLink: 'Donors',
    // One-line description under each dashboard nav card.
    descriptions: {
      collect: 'Log a cash, UPI or bank donation',
      collections: 'Every donation, searchable',
      expenses: 'Record what the mandal spent',
      handovers: 'Cash handed to the treasurer',
      cashInHand: 'What each volunteer is holding',
      volunteers: 'Invite and manage collectors',
      admins: 'Who can manage this mandal',
      donors: 'Donor directory & follow-ups',
      transparency: 'Publish your public fund report',
      settings: 'Identity, branding & payments',
    },
  },
  mandalConfig: {
    title: 'Mandal Settings',
    subtitle: 'Everything donors and volunteers see — update it any time.',
    sectionIdentity: 'Identity',
    sectionIdentityHelp: 'Your name and where you are. Appears on receipts and your public report.',
    sectionBranding: 'Branding',
    sectionBrandingHelp: 'Logo and signature stamped onto every receipt.',
    sectionPayments: 'Payments',
    sectionPaymentsHelp: 'How donors pay you online.',
    sectionBooks: 'Books & receipts',
    nameLabel: 'Mandal name',
    stateLabel: 'State',
    statePlaceholder: 'Select a state',
    addressLabel: 'Address',
    addressHelp: 'Appears on receipts and the public report.',
    creatorPhoneLabel: 'Contact number',
    creatorPhoneHelp: "The mandal contact shown to donors — usually the admin's number.",
    logoLabel: 'Logo',
    signatureLabel: "President's signature",
    changeImage: 'Change',
    uploadImage: 'Upload',
    upiVpaLabel: 'UPI VPA',
    upiVpaPlaceholder: 'mandal@upi',
    upiQrLabel: 'UPI QR code',
    categoriesLabel: 'Expense categories',
    addCategoryPlaceholder: 'Add a category',
    addCategory: 'Add',
    removeCategory: 'Remove category',
    bankOpeningLabel: 'Bank opening balance (₹)',
    defaultLangLabel: 'Default receipt language',
    defaultLangHelp: 'Preselected when a volunteer sends a receipt. They can still change it per donation.',
    uploading: 'Uploading…',
    saveButton: 'Save settings',
    saving: 'Saving…',
    saved: 'Settings saved.',
    backLink: '← Dashboard',
    // F7: city typeahead (fills city + state together)
    cityLabel: 'City',
    cityPlaceholder: 'Start typing your city…',
    cityHelp: 'Pick your city and we fill in the state.',
    cityNotListed: "Can't find your city? Type it and choose “Use as typed”.",
    cityUseAsTyped: 'Use as typed',
    // F3: president name under the receipt signature
    presidentNameLabel: "President's name",
    presidentNamePlaceholder: 'e.g. Shri Madhukar Deshmukh',
    presidentNameHelp: 'Shown under the signature on every receipt.',
    // F3: live receipt preview
    previewReceiptButton: 'Preview donor receipt',
    previewReceiptHint: 'See exactly what a donor receives with your current branding.',
    closePreview: 'Close',
    previewSampleDonor: 'Ramesh Patil',
    // F5: transparency visibility
    sectionTransparency: 'Public report',
    sectionTransparencyHelp: 'Choose who can open your transparency report. Publishing stays separate — set on the report screen.',
    visibilityLabel: 'Who can see the report',
    // F6: receipt inquiry contacts
    sectionContacts: 'Receipt contacts',
    sectionContactsHelp:
      'Shown on every receipt so donors know who to ask. These numbers become public to anyone with a receipt link.',
    contactNameLabel: 'Name',
    contactPhoneLabel: 'Phone',
    contactNamePlaceholder: 'Contact name',
    contactPhonePlaceholder: 'Phone number',
    addContactButton: 'Add another contact',
    removeContact: 'Remove contact',
    contactsMaxHint: 'Up to two extra contacts besides the president.',
    presidentContactTag: 'President · default contact',
    // Shown in place of a president name — never the mandal name (v4 §4).
    previewNoPresidentName: 'No president name set',
    hidePresidentLabel: "Hide the president's number on receipts",
    hidePresidentHelp: 'The president still shows when no other contact is set — donors always have someone to ask.',
  },
  // Top-level, not inside mandalConfig: every language picker (mandal
  // settings, the collection form, pending send) names the languages, and
  // three copies of these four names is three places to drift. Endonyms —
  // a Marathi donor's volunteer looks for "मराठी", not "Marathi", and the
  // surrounding operator UI staying English doesn't change that.
  languages: {
    en: 'English',
    mr: 'मराठी',
    hi: 'हिंदी',
    gu: 'ગુજરાતી',
  },
  volunteers: {
    title: 'Volunteers',
    nameLabel: 'Name',
    phoneLabel: 'Phone (optional)',
    addButton: 'Add volunteer',
    adding: 'Adding…',
    empty: 'No volunteers yet.',
    pending: 'Pending',
    active: 'Active',
    copyLink: 'Copy invite link',
    copied: 'Copied!',
    regenerate: 'Regenerate link',
    regenerating: 'Regenerating…',
    resetInvite: 'Reset & resend',
    resetHint: 'Lost their session (new phone, cleared browser)? Reset to give them a fresh link. Their current access ends until they open it.',
  },
  admins: {
    title: 'Admins',
    nameLabel: 'Name',
    emailLabel: 'Email',
    addButton: 'Add admin',
    adding: 'Adding…',
    empty: 'No admins yet.',
    pending: 'Pending',
    active: 'Active',
    loginHint: "They'll get a login link by entering this email at /login.",
    errors: {
      email: 'Enter a valid email address.',
    },
  },
  collection: {
    title: 'Collect Donation',
    donorNameLabel: 'Donor Name',
    donorPhoneLabel: 'Phone',
    amountLabel: 'Amount (₹)',
    modeLabel: 'Mode',
    modeCash: 'Cash',
    modeUpi: 'UPI',
    modeBank: 'Bank',
    languageLabel: 'Receipt language',
    submitButton: 'Record Donation',
    submitting: 'Recording…',
    successPrefix: 'Receipt #',
    nextDonation: 'Ready for the next donation.',
    sendReceiptSmsButton: 'Send via SMS',
    sendReceiptWhatsAppButton: 'Send via WhatsApp',
    pendingSendLink: 'Pending sends',
    expensesLink: 'Expenses',
    handoversLink: 'Handovers',
    cashInHandLink: 'Cash in hand',
    collectionsLink: 'My collections',
    savedOffline: "Saved — will send once you're back online.",
    // design: greeting + personal daily total chip on the collect form
    greetingPrefix: 'Namaste, ',
    greetingFallback: 'Namaste',
    todayLabel: 'today',
    donorsSuffix: ' donors',
    // design: auspicious quick-amount chips + offline trust microcopy under CTA
    quickAmountsLabel: 'Quick amounts',
    offlineMicrocopy: 'Saved locally first · sends when you press Send',
    // F1 + design: the post-log send tray shown after a donation is recorded
    sendTrayTitle: 'Send from your SMS',
    sendTrayBody: '₹0 cost, and it arrives from you — a trusted neighbour.',
    smsPreviewLabel: 'Message preview',
    openSmsAndSend: 'Open SMS & Send',
    previewReceiptButton: 'Preview donor receipt',
    newCollectionButton: '+ New collection',
    // new-issue #4: donor gave no phone, so there is nobody to text/message
    noPhoneHint: 'No phone number given — receipt cannot be sent.',
    backToDashboard: 'Dashboard',
    // v4: donation source category (remembered per session)
    categoryLabel: 'Source',
    categorySociety: 'Society',
    categoryShop: 'Shop',
    categoryOther: 'Other',
    // v4: bottom-sheet send step
    loggedPrefix: ' logged',
    receiptLabel: 'Receipt ',
    savedOnPhone: 'Saved on phone — will sync when online',
    skipForNow: 'Skip for now',
    closeSheet: 'Close',
    errors: {
      donorName: "Enter the donor's name.",
      donorPhone: 'Enter a valid phone number.',
      amountRupees: 'Enter an amount greater than zero.',
      mode: 'Select a payment mode.',
    },
  },
  collections: {
    title: 'Collections',
    empty: 'No donations recorded yet.',
    receiptPrefix: 'Receipt #',
    deleteButton: 'Delete',
    deleteConfirm: 'Delete donation',
    deleteTitle: 'Delete this donation?',
    deleteBody: "It will be removed from every total and the public report. This can't be undone.",
    deleteReasonLabel: 'Reason (optional)',
    deleteReasonPlaceholder: 'e.g. wrong amount entered',
    voidedPrefix: 'Removed — ',
    removedShow: 'Show removed',
    removedHide: 'Hide removed',
    removedSuffix: ' removed',
    dangerZone: 'Danger zone',
    clearAllButton: 'Clear all donations',
    clearAllHint: 'Removes every donation from your totals and the public report. Records are kept but hidden.',
    clearAllTitle: 'Clear the entire donation history?',
    clearAllBody:
      "Every donation in this mandal will be removed from all totals and the public report. This can't be undone.",
    clearAllConfirm: 'Clear everything',
    clearAllReasonLabel: 'Reason (optional)',
    clearAllReasonPlaceholder: 'e.g. clearing test data',
    clearAllPhraseLabel: 'Type DELETE to confirm',
    clearAllPhrase: 'DELETE',
    cleared: 'Donation history cleared.',
    // v4: expandable row detail
    detailPhone: 'Phone',
    detailCategory: 'Source',
    detailCollectedBy: 'Collected by',
    detailOpenReceipt: 'Open receipt',
    detailCopyLink: 'Copy link',
    detailCall: 'Call',
    detailWhatsApp: 'WhatsApp',
    detailCopied: 'Link copied',
    unknownCollector: 'Unknown',
    // v4: year + source filters
    yearFilterLabel: 'Year',
    allYears: 'All years',
    categoryFilterAll: 'All sources',
    noFilterResults: 'No donations match these filters.',
    keepPastYearsHint: 'Keep past years — use the year filter above instead of clearing.',
    // v4: permanent purge (Danger Zone), separate from the everyday soft "clear"
    purgeRemovedButton: 'Permanently delete removed',
    purgeRemovedHint: 'Erase only the already-removed donations from the database.',
    purgeAllButton: 'Permanently delete ALL history',
    purgeAllHint: 'Erase this mandal’s entire donation history — for a fresh season or test data.',
    purgeConsequence:
      'This cannot be undone. Donor receipt links will stop working, and totals, donor history and the transparency report will change.',
    purgeRemovedTitle: 'Permanently delete removed donations?',
    purgeAllTitle: 'Permanently delete ALL donation history?',
    purgePhraseLabel: 'Type DELETE FOREVER to confirm',
    purgePhrase: 'DELETE FOREVER',
    // The nuclear scope gets its OWN phrase: the two purge buttons sit side by
    // side, and an admin who has typed the removed-only phrase before would
    // otherwise clear the entire ledger from muscle memory after a mis-tap.
    purgeAllPhraseLabel: 'Type ERASE ALL HISTORY to confirm',
    purgeAllPhrase: 'ERASE ALL HISTORY',
    purgeRemovedConfirm: 'Delete removed forever',
    purgeAllConfirm: 'Delete everything forever',
    purgedRemovedNotice: 'Removed donations permanently deleted.',
    purgedAllNotice: 'All donation history permanently deleted.',
  },
  pendingSend: {
    title: 'Pending Send',
    backLink: 'Back to collection',
    empty: 'No pending receipts to send.',
    sendSmsButton: 'SMS',
    sendWhatsAppButton: 'WhatsApp',
    sent: 'Sent!',
    waitingForSignal: 'Waiting for signal',
    needsAttention: 'Needs attention',
    failedPrefix: "Couldn't save: ",
    remove: 'Remove',
    voidButton: 'Delete',
    voidPrompt: 'Reason (optional)',
    voidedPrefix: 'Removed — ',
    // design: "PENDING SEND — N waiting" section header + counter
    sectionTitle: 'Pending send',
    waitingCountSuffix: ' waiting',
    smsPreviewLabel: 'Message preview',
  },
  expenses: {
    title: 'Expenses',
    categoryLabel: 'Category',
    categoryPlaceholder: 'Select a category',
    descriptionLabel: 'Description',
    amountLabel: 'Amount (₹)',
    paidFromLabel: 'Paid from',
    paidFromCash: 'Cash',
    paidFromBank: 'Bank',
    submitButton: 'Log Expense',
    submitting: 'Logging…',
    empty: 'No expenses yet.',
    paidByPrefix: 'Paid by ',
    unknownUser: 'Unknown',
    voidedPrefix: 'Voided — ',
    voidButton: 'Void',
    voidPrompt: 'Reason for voiding this expense:',
    errors: {
      category: 'Select a valid category.',
      amountRupees: 'Enter an amount greater than zero.',
      paidFrom: 'Select cash or bank.',
    },
  },
  handovers: {
    title: 'Handovers',
    amountLabel: 'Amount (₹)',
    receivedByLabel: 'Received by',
    receivedByPlaceholder: 'Select an admin',
    noteLabel: 'Note',
    submitButton: 'Log Handover',
    submitting: 'Logging…',
    empty: 'No handovers yet.',
    volunteerPrefix: 'From ',
    receivedByPrefix: 'To ',
    unknownUser: 'Unknown',
    voidedPrefix: 'Voided — ',
    voidButton: 'Void',
    voidPrompt: 'Reason for voiding this handover:',
    errors: {
      amountRupees: 'Enter an amount greater than zero.',
      receivedBy: 'Select who received the cash.',
    },
  },
  cashInHand: {
    title: 'Cash in Hand',
    empty: 'No active volunteers yet.',
    // design: the maroon "you owe the treasurer" hero (volunteer view)
    youOweLabel: 'You owe the treasurer',
    youOweSubtitle: 'Cash collected, not yet handed over',
    allSettled: "You're all settled up — nothing to hand over right now.",
    // design: three mini stat cards under the hero
    cashCollectedLabel: 'Cash collected',
    spentOnMandalLabel: 'Spent on mandal',
    handedOverLabel: 'Handed over',
    handToTreasurerCta: 'Hand cash to treasurer →',
    myHandoversTitle: 'My handovers',
    // admin view: per-volunteer tracker rows
    withVolunteersSuffix: ' with volunteers',
    stillOwesLabel: 'still owes',
    collectedPrefix: 'collected ',
    handedPrefix: 'handed ',
  },
  // v4: admin donor directory (donors_summary RPC)
  donors: {
    title: 'Donors',
    subtitle: 'Who gave what — tap a donor to call or message for follow-ups.',
    empty: 'No donations yet.',
    searchPlaceholder: 'Search name or phone…',
    totalGivenLabel: 'Total given',
    donationsLabel: 'donations',
    firstLabel: 'First',
    lastLabel: 'Last',
    call: 'Call',
    whatsApp: 'WhatsApp',
    historyTitle: 'Donation history',
    yearFilterLabel: 'Year',
    allYears: 'All years',
    anonymous: 'Unnamed donor',
    noPhone: 'No phone',
  },
  transparency: {
    title: 'Transparency Report',
    totalCollectedLabel: 'Total collected from society',
    reportEyebrow: 'Ganeshotsav 2026 · Fund Report',
    usageTitle: 'How the funds were used',
    spentLabel: 'Spent so far',
    inHandLabel: 'Still in hand',
    footerNote: 'Every rupee, accounted for. Ganpati Bappa Morya 🙏',
    noExpenses: 'No expenses recorded yet.',
    otherCategory: 'Other',
    notPublished: 'The transparency report has not been published yet.',
    publishButton: 'Publish',
    unpublishButton: 'Unpublish',
    publishedStatus: 'Visible to the public.',
    unpublishedStatus: 'Not visible to the public yet.',
    publicLinkLabel: 'Public link',
    copyLink: 'Copy link',
    copied: 'Copied',
    // design: donor-count line + verbatim privacy note on the public report
    acrossFamiliesPrefix: 'across ',
    acrossFamiliesSuffix: ' families — with heartfelt thanks',
    familyPrefix: 'across ',
    familySuffix: ' family — with heartfelt thanks',
    privacyNote:
      'Individual donor names and amounts are kept private. This report shows only the mandal’s totals — complete transparency, in one glance. 🙏',
    // F5: shown when visibility is 'disabled' (or a members/admins report the
    // viewer isn't allowed to see) instead of the "not published" copy.
    reportNotAvailable: 'This report is not available.',
    // F5 admin badge
    visibilityBadgePrefix: 'Visibility · ',
    visibilityLabel: 'Who can see it',
    // v3: floating home link on the public report / landing sample
    homeLink: 'Digital Vargani',
  },
  // Top-level (shared by Mandal Settings' radio picker and the admin
  // transparency badge), same rationale as `languages` above — one place for
  // the four visibility labels so the two screens can't drift.
  transparencyVisibility: {
    public: 'Anyone with the link',
    members: 'Signed-in members of this mandal',
    admins: 'Admins of this mandal only',
    disabled: 'Nobody — report turned off',
    publicHelp: 'Today’s behaviour — anyone you share the link with can open it.',
    membersHelp: 'Only your volunteers and admins, after they sign in.',
    adminsHelp: 'Only this mandal’s admins.',
    disabledHelp: 'The link shows a friendly “not available” message to everyone.',
  },
  ledger: {
    totalCollectedLabel: 'Total Collected',
    totalExpensesLabel: 'Total Expenses',
    netBalanceLabel: 'Net Balance',
    balanced: 'Books balanced',
    discrepancyPrefix: 'Discrepancy: ',
    // F9 admin dashboard redesign (treasurer console)
    consoleTitle: 'Treasurer console',
    masterLedgerTitle: 'Master Ledger',
    liveSubtitle: 'Live view · updated just now',
    // books-balance equation banner, real numbers
    booksBalanceTitle: 'Books balance — everything reconciles',
    booksImbalanceTitle: 'Books don’t balance yet',
    equationNetLabel: 'Net Balance',
    equationOpeningLabel: 'Opening balance',
    equationVolunteers: 'Volunteers',
    equationTreasurer: 'Treasurer cash',
    equationBank: 'Bank',
    inactiveVolunteersLabel: 'Inactive volunteers',
    // v3: 4th stat tile on the mobile 2×2 dashboard grid
    cashWithVolunteersLabel: 'Cash w/ volunteers',
    // stat trio
    fundPoolLabel: 'Total fund pool',
    donationsCountSuffix: ' donations collected',
    paymentsCountSuffix: ' payments made',
    netBalanceSubtitle: 'Collections − Expenses',
    // two-column body
    cashTrackerTitle: 'Cash in hand',
    withVolunteersSuffix: ' with volunteers',
    stillOwesLabel: 'still owes',
    collectedPrefix: 'collected ',
    handedPrefix: 'handed ',
    whereMoneyWentTitle: 'Where the money went',
    noExpensesYet: 'No expenses recorded yet.',
    // v4: "where money came from" (source split) + collections insight
    whereMoneyCameFromTitle: 'Where the money came from',
    sourceSocietyLabel: 'Society',
    sourceShopLabel: 'Shop',
    sourceOtherLabel: 'Other',
    donationsCountLabel: 'donations',
    noDonationsYet: 'No donations recorded yet.',
    insightTitle: 'Collections insight',
    insightTotalDonations: 'Donations',
    insightUniqueDonors: 'Unique donors',
    insightAvgDonation: 'Average',
    insightLargestDonation: 'Largest',
  },
  landing: {
    productName: 'Digital Vargani',
    productSubtitle: 'Fund system for mandals',
    nav: {
      whatItIs: 'What it is',
      features: 'Features',
      howItWorks: 'How it works',
      login: 'Log in',
      startFree: 'Start free →',
    },
    hero: {
      badge: 'Ganeshotsav · वर्गणी, digitised',
      titleLead: 'Every rupee of vargani, ',
      titleHighlight: 'accounted for.',
      subtitle:
        "Digital Vargani turns your mandal's paper bill book into instant mobile collections, a live treasurer dashboard, and receipts donors actually trust — for any Ganesh mandal, at zero cost.",
      ctaPrimary: 'Start your mandal free',
      ctaSecondary: 'See how it works ↓',
      trustLine1: 'Trusted by mandals big and small',
      trustLine2: 'Zero cost · no app store · works on any phone',
    },
    demoPhone: {
      mandalName: 'Vinayak Yuvak Mandal',
      liveLabel: 'Live · collecting now',
      collectedTodayLabel: 'Collected today',
      donorsLabel: 'donors',
      reconciledLabel: 'reconciled',
      syncedLabel: '✓ synced',
      recentCollectionsLabel: 'Recent collections',
      receiptSentLabel: '✓ receipt sent',
      sentToDonor: '✓ Sent to donor',
      mark: '॥ श्री गणेशाय नमः ॥',
    },
    stats: [
      { value: '₹0', label: 'cost, forever' },
      { value: '10s', label: 'to log a donation' },
      { value: '100%', label: 'receipts, no paper' },
      { value: '∞', label: 'mandals, one login' },
    ],
    whatItIs: {
      eyebrow: 'What is Digital Vargani',
      title: 'The bill book, without the book.',
      body: 'For decades, vargani meant carbon-copy receipt books, a locked cash box, and a register nobody outside the committee ever saw. Digital Vargani keeps the trust of that ritual — and removes the paper, the guesswork, and the "where did the money go?"',
      beforeLabel: 'Before · on paper',
      afterLabel: 'After · Digital Vargani',
      before: [
        'Carbon-copy receipt books',
        'Cash box nobody can audit',
        'Totals added up by hand at night',
        'A register the public never sees',
      ],
      after: [
        'Log a donation in 10 seconds',
        'Cash-in-hand tracked live',
        'Reconciliation checks itself',
        'A public report anyone can open',
      ],
    },
    features: {
      eyebrow: 'Everything the committee needs',
      title: 'One system, from the donation at the door to the report on the wall.',
      items: [
        {
          icon: '📲',
          title: 'Mobile collection',
          desc: 'Volunteers log cash, UPI or bank donations from any phone in seconds — no app store, no training.',
        },
        {
          icon: '🧾',
          title: 'Instant digital receipts',
          desc: 'Receipts go out over SMS or WhatsApp from your own number, at ₹0 cost — from a neighbour donors trust.',
        },
        {
          icon: '📊',
          title: 'Live treasurer dashboard',
          desc: 'Watch totals, cash-in-hand and every volunteer update in real time as money comes in.',
        },
        {
          icon: '⚖️',
          title: 'Self-checking reconciliation',
          desc: 'Every rupee collected is matched against what was handed over. Mismatches get flagged instantly.',
        },
        {
          icon: '🪷',
          title: 'Public transparency report',
          desc: 'One shareable page shows donors exactly what came in and where every rupee went.',
        },
        {
          icon: '🏛️',
          title: 'Multi-mandal, one login',
          desc: 'Run every mandal in your trust, ward or federation from a single dashboard that adds them all up.',
          isNew: true,
        },
      ],
    },
    howItWorks: {
      eyebrow: 'How it works',
      title: 'Live for your mandal in one evening.',
      steps: [
        {
          n: '1',
          title: 'Add your mandal',
          desc: 'Name, area and deity — done in two minutes. Upload your logo and the receipts carry your identity.',
        },
        {
          n: '2',
          title: 'Volunteers collect',
          desc: 'Share a link. Volunteers open it, log donations at the door and send receipts on the spot.',
        },
        {
          n: '3',
          title: 'Everyone sees the truth',
          desc: 'The treasurer reconciles, donors keep their receipts, and the public opens a report they can trust.',
        },
      ],
    },
    multiMandal: {
      badge: 'New · multi-mandal',
      title: 'For every mandal — big or small.',
      body: 'Officially registered or not, big or small — any Ganesh mandal can use Digital Vargani. Each mandal stays fully private — its own volunteers, receipts, reports and data, kept completely separate from every other.',
      points: [
        'Works for any mandal — officially registered or not',
        'Every mandal is fully private with its own identity',
        'Its own volunteers, receipts, cash books and data',
      ],
      panelTitle: 'Trusted by mandals like',
      panelSubtitle: 'Each one private · its own data & identity',
      moreJoining: '+ more joining',
      activeLabel: 'Active',
    },
    transparency: {
      eyebrow: 'Trust, made visible',
      title: 'Every donor gets a receipt. Every rupee gets a report.',
      body: 'Receipts go out over SMS or WhatsApp from your own number — ₹0 cost, and they arrive from a neighbour donors already trust. At the end, one shareable public page shows exactly what came in and where it went.',
      cta: 'See a sample report →',
      sample: {
        eyebrow: 'Ganeshotsav 2026 · Fund Report',
        totalLabel: 'Total collected from society',
        totalNote: 'across 128 families — with heartfelt thanks',
        usageTitle: 'How the funds were used',
        // Rupee amounts; FundDonut computes the % and formats each figure.
        categories: [
          { name: 'Mandap & Decoration', value: 98200, color: '#e2680f' },
          { name: 'Prasad & Bhog', value: 61400, color: '#2f7d44' },
          { name: 'Sound & Lighting', value: 42000, color: '#dca02c' },
          { name: 'Idol & Puja', value: 27600, color: '#c0442e' },
          { name: 'Other', value: 16600, color: '#a8998a' },
        ],
      },
    },
    multilingual: {
      badge: 'New · multilingual receipts',
      title: "Send the receipt in the donor's own language.",
      body: "English is the default, but before sending, the volunteer can switch the receipt to Gujarati, Hindi or Marathi — so every donor gets a receipt they can read at a glance.",
      points: [
        'English by default on every receipt',
        'Volunteer picks the language before sending',
        'Gujarati, Hindi, Marathi & English supported',
      ],
      sendInLabel: 'Send receipt in',
      sendWhatsapp: 'Send on WhatsApp',
      langs: [
        { code: 'en', native: 'English', tag: 'Primary' },
        { code: 'gu', native: 'ગુજરાતી', tag: 'Gujarati' },
        { code: 'hi', native: 'हिन्दी', tag: 'Hindi' },
        { code: 'mr', native: 'मराठी', tag: 'Marathi' },
      ],
      translations: {
        en: {
          subtitle: 'Official donation receipt',
          noLabel: 'Receipt no.',
          donorLabel: 'Donor',
          amountLabel: 'Amount',
          thanks: 'Thank you for your vargani. Ganpati Bappa Morya!',
        },
        gu: {
          subtitle: 'સત્તાવાર દાન રસીદ',
          noLabel: 'રસીદ નં.',
          donorLabel: 'દાતા',
          amountLabel: 'રકમ',
          thanks: 'તમારા દાન બદલ આભાર. ગણપતિ બાપ્પા મોર્યા!',
        },
        hi: {
          subtitle: 'आधिकारिक दान रसीद',
          noLabel: 'रसीद क्र.',
          donorLabel: 'दाता',
          amountLabel: 'राशि',
          thanks: 'आपकी वर्गणी के लिए धन्यवाद। गणपति बाप्पा मोरया!',
        },
        mr: {
          subtitle: 'अधिकृत देणगी पावती',
          noLabel: 'पावती क्र.',
          donorLabel: 'देणगीदार',
          amountLabel: 'रक्कम',
          thanks: 'तुमच्या वर्गणीसाठी धन्यवाद. गणपती बाप्पा मोरया!',
        },
      },
    },
    finalCta: {
      mark: '॥',
      title: 'Ready for a paperless Ganeshotsav?',
      body: 'Set up your mandal in minutes. No app to install, no fees, no fine print — just cleaner collections and complete trust.',
      ctaPrimary: 'Start your mandal free',
    },
    footer: {
      tagline: 'Made with devotion for mandals everywhere',
      copyright: '© 2026 · Ganpati Bappa Morya',
    },
  },
}
