-- Plan 2026-08-18 §1 — custom donation sources.
--
-- Replaces the fixed Society/Shop/Other triple with a per-mandal, renameable
-- list (cap 6, enforced in the RPC and the client). Additive and live-safe:
-- nothing existing is UPDATEd or DELETEd, forbid_financial_edit() is left
-- exactly as it is, and old clients keep inserting the three lowercase slugs
-- which stay valid under the relaxed CHECK.
--
-- The append-only trick that makes renames safe: a NEW donation stores the
-- source NAME as text in donations.category; a LEGACY row keeps its
-- 'society'/'shop'/'other' slug and is displayed through a fixed label map on
-- the client (lib/sources.ts). Renaming or removing a source therefore never
-- touches a single donation row — the past keeps the name it was logged under.

-- ── 1. Per-mandal source list (mirrors expense_categories exactly) ───────
alter table mandals
  add column donation_sources text[] not null default '{Society,Shop,Other}';

-- ── 2. Relax the fixed CHECK on donations.category ──────────────────────
-- Metadata-only: dropping and re-adding a CHECK rewrites no rows. Every
-- existing 'society'/'shop'/'other' value satisfies the new predicate, so the
-- ADD validates without touching data. The column's own default ('society')
-- deliberately stays — the form always sends a value, and a stale offline
-- client syncing an old-style row must remain valid.
--
-- Constraint name is discovered rather than hardcoded: it was auto-generated by
-- `alter table donations add column category text ... check (...)` in
-- 20260719140000, and the only check on this table mentioning `category` is
-- that one (the others are amount_paise > 0 and mode in (...)).
do $$
declare v_conname text;
begin
  select conname into v_conname
  from pg_constraint
  where conrelid = 'donations'::regclass
    and contype = 'c'
    and pg_get_constraintdef(oid) like '%category%';
  if v_conname is not null then
    execute format('alter table donations drop constraint %I', v_conname);
  end if;
end $$;

alter table donations add constraint donations_category_check
  check (length(btrim(category)) > 0 and length(category) <= 40);

-- ── 3. Read RPC so VOLUNTEERS can see the list ──────────────────────────
-- mandals' select policy is admin-only, so a volunteer session gets zero rows
-- from getMandal(). Same narrowly-scoped SECURITY DEFINER shape as
-- get_expense_categories(): one column, scoped to app_mandal_id() server-side.
create or replace function get_donation_sources() returns text[]
language sql stable security definer set search_path = public as $$
  select donation_sources from mandals where id = app_mandal_id()
$$;

revoke execute on function get_donation_sources() from public;
revoke execute on function get_donation_sources() from anon;
grant execute on function get_donation_sources() to authenticated;

-- ── 4. add_donation_source: the ONLY volunteer write path ───────────────
-- Decided open question 1 (user, 2026-08-18): volunteers may ADD a source
-- (they are the ones standing at a shop that doesn't fit "Society"), while
-- rename/remove stay admin-only through updateMandal + the existing
-- mandals_admin_update policy. mandals' UPDATE RLS is deliberately NOT
-- widened — this function is the whole of the volunteer's write surface.
--
-- `for update` takes the mandal row lock, so two volunteers adding at the same
-- moment serialize: the second sees the first's row and gets the duplicate or
-- cap error rather than both slipping through.
create or replace function add_donation_source(p_name text) returns text[]
language plpgsql security definer set search_path = public as $$
declare
  v_mandal uuid := app_mandal_id();
  v_name   text := btrim(coalesce(p_name, ''));
  v_list   text[];
begin
  -- app_mandal_id() already requires an ACTIVE users row for auth.uid(), so a
  -- non-member (or a deactivated ex-member) resolves to null here.
  if v_mandal is null then
    raise exception 'no mandal for the current session';
  end if;
  if v_name = '' then
    raise exception 'a donation source needs a name';
  end if;
  if length(v_name) > 40 then
    raise exception 'a donation source name is at most 40 characters';
  end if;

  select donation_sources into v_list from mandals where id = v_mandal for update;
  if v_list is null then
    raise exception 'no mandal for the current session';
  end if;

  if exists (select 1 from unnest(v_list) s where lower(s) = lower(v_name)) then
    raise exception 'that donation source already exists';
  end if;
  -- array_length is NULL on an empty array; NULL >= 6 is not true, so an
  -- emptied list correctly still accepts an add.
  if coalesce(array_length(v_list, 1), 0) >= 6 then
    raise exception 'six donation sources is the maximum';
  end if;

  update mandals set donation_sources = v_list || v_name
  where id = v_mandal
  returning donation_sources into v_list;

  return v_list;
end $$;

revoke execute on function add_donation_source(text) from public;
revoke execute on function add_donation_source(text) from anon;
grant execute on function add_donation_source(text) to authenticated;
